import {jsPDF} from 'jspdf';
import {Data,Handover,shots} from './domain';
import {companyLogo,stockLabels,vehicleTitle} from './company';
import {equipmentLabel} from './vehicle-catalog';
import {purposeLabels} from './protocol';
import {supabase} from './supabase';
import {protocolDamages,validDamageMarker} from './damages';
import {damageDiagramImage} from './damage-diagram-image';
async function imageData(url:string){if(url.startsWith('data:'))return url;const r=await fetch(url);if(!r.ok)throw Error('Bild konnte nicht geladen werden. Bitte erneut versuchen.');const blob=await r.blob();return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(blob);});}
export async function exportModernProtocol(data:Data,h:Handover){
 const snapshot=h.snapshot!,v=snapshot.vehicle,org=snapshot.organization!,profile=org.profile??{},pdf=new jsPDF(),reference=snapshot.order?.reference??h.id.slice(0,8).toUpperCase();let y=22;
 const line=(text:string,size=10,width=170)=>{pdf.setFontSize(size);const lines=pdf.splitTextToSize(text,width);for(const value of lines){if(y>266){pdf.addPage();y=24;}pdf.text(value,20,y);y+=Math.max(size<10?4:5,size*.38);}y+=2;};
 const section=(title:string)=>{if(y>244){pdf.addPage();y=24;}y+=5;pdf.setFillColor(235,240,247);pdf.roundedRect(18,y-5,174,10,2,2,'F');pdf.setFont('helvetica','bold');line(title,11);pdf.setFont('helvetica','normal');y+=3;};
 const logo=await companyLogo(org,!!supabase);if(logo){const src=await imageData(logo),props=pdf.getImageProperties(src),scale=Math.min(45/props.width,22/props.height);pdf.addImage(src,'PNG',145,15,props.width*scale,props.height*scale);}
 pdf.setTextColor(25,43,66);pdf.setFont('helvetica','bold');line(org.name,15,logo?115:170);pdf.setFont('helvetica','normal');line([profile.street,[profile.postal_code,profile.city].filter(Boolean).join(' '),profile.country].filter(Boolean).join(' · '),9);line([profile.email,profile.phone,profile.website].filter(Boolean).join(' · '),9);y=Math.max(y,50);
 line(h.kind==='pickup'?'Fahrzeugübernahme':'Fahrzeugübergabe',23);line(`${purposeLabels[h.purpose??'other']} · ${reference} · ${new Date(h.created_at).toLocaleString('de-DE')}`,10);
 section('Fahrzeug und Vorgang');line(vehicleTitle(v),13);line(`Bestandsnummer: ${v.stock_number??'Nicht erfasst'} | VIN: ${v.vin}`);line(`Zulassungskennzeichen: ${v.plate??'Nicht zugeordnet'} | Transportkennzeichen: ${h.transport_plate||'Nicht angegeben'}`);line(`Farbe: ${v.color}${v.build_year?' | Baujahr: '+v.build_year:''}${v.first_registration?' | Erstzulassung: '+v.first_registration:''}`);if(snapshot.order)line(`Route: ${snapshot.order.pickup} > ${snapshot.order.destination}`);if(h.position)line(`${h.position.confirmed===false||h.kind==='pickup'&&snapshot.order&&!h.position.confirmed?'Vorgangsort':'Bestätigte Position'}: ${h.position.location}${h.position.space_label?' · '+h.position.space_label:''}`);
 if(v.variant)line('Ausführung: '+v.variant);if(v.equipment?.length)line('Ausstattung: '+v.equipment.map(equipmentLabel).join(', '));if(v.equipment_notes)line('Weitere Ausstattung: '+v.equipment_notes);section('Beteiligte und Fahrzeugzustand');line(`Übergebend: ${h.parties!.giver.name} (${h.parties!.giver.role})`);line(`Übernehmend: ${h.parties!.receiver.name} (${h.parties!.receiver.role})`);line(`Kilometerstand: ${h.mileage.toLocaleString('de-DE')} km | Tank/Ladung: ${h.fuel} %`);if(v.inventory_kind==='owned')line(`Bestandsstatus: ${v.inventory_status?stockLabels[v.inventory_status]:'Nicht erfasst'} > ${h.position?.stock_status?stockLabels[h.position.stock_status]:'Nicht erfasst'}`);
 section('Schäden, Schlüssel und Hinweise');for(const d of snapshot.known_damages??[])line('Bekannter Schaden · '+d.area+': '+d.description);const damages=protocolDamages(data,h);if(!damages.length)line('Keine neuen Schäden dokumentiert.');damages.forEach((d,i)=>line((snapshot.new_damages?'Neuer Schaden '+(i+1)+' · ':'')+d.area+': '+d.description));if(!h.key_snapshot?.recorded)line('Schlüsselbestand nicht erfasst.');else{line(`${h.key_snapshot.selected.length} von ${h.key_snapshot.expected_count} erfassten aktiven Schlüsseln bestätigt.`);h.key_snapshot.selected.forEach(k=>line(k.label+(k.identifier?' · '+k.identifier:'')));if(h.key_snapshot.notes)line('Schlüsselabweichung: '+h.key_snapshot.notes);}line('Hinweise: '+(h.notes||'Keine'));
 const exceptionHeight=h.parties!.exception_confirmed?Math.min(60,pdf.splitTextToSize('Ausnahme: '+h.parties!.exception_reason,170).length*7):0;
 if(y>203-exceptionHeight){pdf.addPage();y=24;}section('Bestätigung und Unterschriften');line('Die Beteiligten bestätigen den dokumentierten Fahrzeugzustand.',9);const top=y;for(const [index,party]of[h.parties!.giver,h.parties!.receiver].entries()){const x=index?111:20;pdf.setFontSize(9);pdf.text(index?'Übernehmende Person':'Übergebende Person',x,top);pdf.text(pdf.splitTextToSize(party.name+' · '+party.role,78),x,top+6);const url=party.signature_url??party.signature;if(url){const image=await imageData(url),props=pdf.getImageProperties(image),scale=Math.min(76/props.width,24/props.height);pdf.addImage(image,'PNG',x,top+18,props.width*scale,props.height*scale);}else pdf.text('Unterschrift fehlt – begründete Ausnahme',x,top+27);pdf.setDrawColor(180,190,204);pdf.line(x,top+45,x+78,top+45);}y=top+50;if(h.parties!.exception_confirmed)line('Ausnahme: '+h.parties!.exception_reason);
 const photos=[...h.photos].sort((a,b)=>shots.indexOf(a.slot as typeof shots[number])-shots.indexOf(b.slot as typeof shots[number]));let interior=0;
 for(let index=0;index<photos.length;index++){if(index%4===0){pdf.addPage();y=28;line('Fotodokumentation',18);}const column=index%2,row=Math.floor(index%4/2),x=20+column*88,top=48+row*108,p=photos[index];pdf.setFontSize(10);pdf.text(p.slot==='Innenraum'?'Innenraum '+(++interior)+' / '+photos.filter(p=>p.slot==='Innenraum').length:p.slot,x,top);const image=await imageData(p.url),props=pdf.getImageProperties(image),scale=Math.min(80/props.width,87/props.height);pdf.addImage(image,'JPEG',x+(80-props.width*scale)/2,top+6,props.width*scale,props.height*scale,undefined,'FAST');}
 const known=snapshot.known_damages??[];
 if(snapshot.new_damages&&[...known,...damages].some(d=>validDamageMarker(d.marker))){pdf.addPage();y=26;line('Schadenübersicht',18);line('Vorne oben · Fahrzeug links / rechts wie im Rundgang',9);pdf.addImage(await damageDiagramImage(known,damages),'PNG',24,50,55,105);y=50;const all=[...known.map((d,i)=>({d,label:'B'+(i+1)+' · Bekannt'})),...damages.map((d,i)=>({d,label:'N'+(i+1)+' · Neu'}))];for(const {d,label}of all){if(y>251){pdf.addPage();y=28;}pdf.setFontSize(9);const lines=pdf.splitTextToSize(label+' · '+d.area,104);pdf.text(lines,88,y);y+=lines.length*5+3;}y=Math.max(y,162);}
 const damagePhotos=snapshot.new_damages?[...known.map((d,i)=>({d,label:'B'+(i+1)+' · Bekannt'})),...damages.map((d,i)=>({d,label:'N'+(i+1)+' · Neu'}))].flatMap(({d,label})=>(d.photos??[]).map((p,i)=>({p,caption:label+' · '+d.area+' · Detailfoto '+(i+1)}))):[];
 for(let index=0;index<damagePhotos.length;index++){if(index%4===0){pdf.addPage();y=28;line('Schadenfotos',18);}const column=index%2,row=Math.floor(index%4/2),x=20+column*88,top=48+row*108,{p,caption}=damagePhotos[index];pdf.setFontSize(8);const captionLines=pdf.splitTextToSize(caption,80).slice(0,3);pdf.text(captionLines,x,top);const image=await imageData(p.url),props=pdf.getImageProperties(image),scale=Math.min(80/props.width,79/props.height);pdf.addImage(image,'JPEG',x+(80-props.width*scale)/2,top+15,props.width*scale,props.height*scale,undefined,'FAST');}
 const pages=pdf.getNumberOfPages();for(let page=1;page<=pages;page++){pdf.setPage(page);pdf.setFontSize(7);pdf.setTextColor(95,110,130);const legal=[profile.legal_form,profile.management&&'Vertreten durch '+profile.management,profile.tax_number&&'St-Nr. '+profile.tax_number,profile.vat_id&&'USt-ID '+profile.vat_id,profile.register_court,profile.register_number].filter(Boolean).join(' · ');pdf.text(pdf.splitTextToSize(legal,172).slice(0,2),20,279);pdf.text(`${reference} · ${h.kind==='pickup'?'Übernahme':'Übergabe'} · ${h.id} · Seite ${page}/${pages}`,20,292);}
 pdf.save(`${reference}-${h.kind==='pickup'?'Uebernahme':'Uebergabe'}.pdf`);
}
