import {Data,Handover,Kind,Order,ProtocolDraft,Vehicle,Purpose,StockStatus,shots,requiredPhotoCount} from './domain';
import {loadCloud,mutateDemo} from './repository';
import {supabase} from './supabase';
import {keySnapshot,keyValidation} from './vehicle-records';
import {recordMovement} from './inventory-domain';
import type {Json} from './database.types';
export const purposeLabels:Record<Purpose,string>={transport:'Überführung',purchase:'Ankauf',sale:'Verkauf',rental:'Vermietung',return:'Rücknahme',other:'Sonstiges'};
export function suggestedStatus(vehicle:Vehicle,kind:Kind,purpose:Purpose):StockStatus|''{if(vehicle.inventory_kind!=='owned')return '';if(kind==='pickup'&&['purchase','return'].includes(purpose))return 'stock';if(kind==='delivery'&&purpose==='sale')return 'sold';if(kind==='delivery'&&purpose==='rental')return 'rented';return vehicle.inventory_status??'';}
export function initialProtocol(data:Data,v:Vehicle,order:Order|null,kind:Kind):ProtocolDraft{return {id:crypto.randomUUID(),purpose:order?'transport':'other',mileage:v.mileage,fuel:75,signer:'',signature:'',notes:'',photos:[],damages:[],keys:{confirmed:false,selected:[],notes:'',revision:v.keys_revision??1},company_revision:data.organization.revision??1,vehicle_revision:v.revision??1,order_revision:order?.revision??null,transport_plate:order?.transport_plate??'',parties:{giver:{name:'',role:'',signature:''},receiver:{name:'',role:'',signature:''},exception_confirmed:false,exception_reason:''},position:{location:kind==='pickup'?order?.pickup??v.location:order?.destination??v.location,site_id:order?null:v.site_id??null,space_id:order?null:v.parking_space_id??null,confirmed:false},stock_status:v.inventory_status??'',stock_confirmed:false};}
export function protocolErrors(data:Data,v:Vehicle,d:ProtocolDraft,standalone:boolean):string[]{const errors:string[]=[];
 if(!Number.isSafeInteger(d.mileage)||d.mileage<v.mileage)errors.push('Kilometerstand darf nicht sinken.');if(!Number.isSafeInteger(d.fuel)||d.fuel<0||d.fuel>100)errors.push('Tank-/Ladestand muss zwischen 0 und 100 liegen.');
 if(!d.parties.giver.name.trim()||!d.parties.receiver.name.trim()||!d.parties.giver.role.trim()||!d.parties.receiver.role.trim())errors.push('Beide Beteiligten benötigen Name und Funktion.');
 if(d.photos.some(p=>!shots.some(slot=>slot===p.slot)||!p.url.startsWith('data:image/jpeg;base64,'))||shots.some(slot=>slot!=='Innenraum'&&d.photos.filter(p=>p.slot===slot).length>1))errors.push('Fotodokumentation ungültig.');
 if(requiredPhotoCount(d.photos)!==10)errors.push('Alle zehn Fotoperspektiven aufnehmen.');
 for(const role of ['giver','receiver'] as const)if(d.parties[role].signature&&!d.parties[role].signature.startsWith('data:image/png;base64,'))errors.push('Unterschrift ungültig.');
 if(!d.parties.giver.signature&&!d.parties.receiver.signature)errors.push('Mindestens eine Unterschrift erforderlich.');
 if((!d.parties.giver.signature||!d.parties.receiver.signature)&&(!d.parties.exception_confirmed||!d.parties.exception_reason.trim()))errors.push('Fehlende Unterschrift: Ausnahme bestätigen und begründen.');
 if(d.damages.some(d=>!d.area.trim()||!d.description.trim()))errors.push('Schaden benötigt Bereich und Beschreibung.');
 if(standalone&&!d.position.confirmed)errors.push('Tatsächliche Position bestätigen.');if(standalone&&!d.position.site_id&&!d.position.location.trim())errors.push('Position fehlt.');if(standalone&&v.inventory_kind==='owned'&&!d.stock_confirmed)errors.push('Bestandsstatus bestätigen.');
 if(d.company_revision!==(data.organization.revision??1))errors.push('Unternehmensprofil geändert. Bitte Entwurf neu prüfen.');return [...errors,...keyValidation(data,v,d)];
}
export function updateProtocol(d:ProtocolDraft,patch:Partial<ProtocolDraft>,signing=false):ProtocolDraft {const next={...d,...patch};return signing?next:{...next,parties:{...next.parties,giver:{...next.parties.giver,signature:''},receiver:{...next.parties.receiver,signature:''}}};}
async function upload(d:ProtocolDraft,org:string,url:string,label:string,write=true){const blob=await(await fetch(url)).blob(),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))).map(n=>n.toString(16).padStart(2,'0')).join('');const path=org+'/'+d.id+'/'+label+'-'+hash+(blob.type==='image/png'?'.png':'.jpg');if(!write)return path;const r=await supabase!.storage.from('protocol-media').upload(path,blob,{contentType:blob.type,upsert:false});if(r.error&&!/already exists|duplicate/i.test(r.error.message))throw Error(r.error.message);return path;}
export async function finalizeProtocol(data:Data,v:Vehicle,order:Order|null,kind:Kind,d:ProtocolDraft,cloud:boolean):Promise<Data>{
 const errors=protocolErrors(data,v,d,!order);if(errors.length)throw Error(errors[0]);
 if(cloud){const existing=await supabase!.from('handovers').select('id').eq('id',d.id).maybeSingle();if(existing.error)throw Error(existing.error.message);if(!existing.data){const start=await supabase!.rpc('start_protocol',{p_id:d.id,p_vehicle:v.id,p_order:order?.id as unknown as string??null as unknown as string,p_kind:kind});if(start.error)throw Error(start.error.message);}
  const photos=[];for(let i=0;i<d.photos.length;i++)photos.push({slot:d.photos[i].slot,path:await upload(d,data.organization.id,d.photos[i].url,'photo-'+i,!existing.data)});
  const parties={...d.parties,giver:{...d.parties.giver,signature:d.parties.giver.signature?await upload(d,data.organization.id,d.parties.giver.signature,'giver',!existing.data):''},receiver:{...d.parties.receiver,signature:d.parties.receiver.signature?await upload(d,data.organization.id,d.parties.receiver.signature,'receiver',!existing.data):''}};
  const r=await supabase!.rpc('finalize_protocol',{p_id:d.id,p_values:{purpose:d.purpose,mileage:d.mileage,fuel:d.fuel,company_revision:d.company_revision,vehicle_revision:d.vehicle_revision,order_revision:d.order_revision,notes:d.notes,photos,damages:d.damages,keys:d.keys,parties,position:d.position,stock_status:d.stock_status||null,stock_confirmed:d.stock_confirmed,transport_plate:d.transport_plate} as unknown as Json});if(r.error)throw Error(r.error.message);return(await loadCloud(data.organization.id))!;
 }
 const fingerprint=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(d))))).map(n=>n.toString(16).padStart(2,'0')).join('');
 return mutateDemo(latest=>{const old=latest.handovers.find(h=>h.id===d.id);if(old){if(old.request_hash!==fingerprint)throw Error('Protokoll-ID mit anderem Inhalt abgeschlossen');return latest;}const current=latest.vehicles.find(row=>row.id===v.id)!;if((current.revision??1)!==d.vehicle_revision)throw Error('Fahrzeug wurde geändert. Bitte neu prüfen.');const currentOrder=order?latest.orders.find(o=>o.id===order.id):null;if(order&&(!currentOrder||(currentOrder.revision??1)!==d.order_revision||currentOrder.status!==(kind==='pickup'?'assigned':'in_transit')))throw Error('Auftrag wurde geändert.');if(!order&&latest.orders.some(o=>o.vehicle_id===v.id&&o.status==='in_transit'))throw Error('Fahrzeug ist in Transport');const issues=protocolErrors(latest,current,d,!order);if(issues.length)throw Error(issues[0]);const now=new Date().toISOString(),location=order?(kind==='pickup'?'In Transport':order.destination):d.position.site_id?latest.sites?.find(s=>s.id===d.position.site_id)?.name??'':d.position.location;
 const site=order?null:d.position.site_id??null,space=order?null:d.position.space_id??null;if(site&&!latest.sites?.some(s=>s.id===site&&s.organization_id===v.organization_id))throw Error('Standort gehört nicht zum Unternehmen.');if(space&&!latest.spaces?.some(s=>s.id===space&&s.site_id===site&&s.organization_id===v.organization_id))throw Error('Stellplatz gehört nicht zum Standort.');if(space&&latest.vehicles.some(row=>row.id!==v.id&&row.parking_space_id===space))throw Error('Stellplatz belegt.');
 const selected=keySnapshot(latest,current,d),h:Handover={id:d.id,organization_id:latest.organization.id,vehicle_id:v.id,order_id:order?.id??null,version:2,request_hash:fingerprint,kind,purpose:d.purpose,mileage:d.mileage,fuel:d.fuel,signer:d.parties.receiver.signature?d.parties.receiver.name:d.parties.giver.name,signature:d.parties.receiver.signature||d.parties.giver.signature,notes:d.notes,created_at:now,photos:d.photos.map(p=>({...p})),parties:structuredClone(d.parties),position:{...d.position,location,space_label:latest.spaces?.find(s=>s.id===space)?.label??null,stock_status:!order&&current.inventory_kind==='owned'?d.stock_status||null:current.inventory_status??null},transport_plate:d.transport_plate,key_snapshot:selected,snapshot:{organization_name:latest.organization.name,organization:structuredClone(latest.organization),known_damages:latest.damages.filter(d=>d.vehicle_id===v.id).map(({id,area,description})=>({id,area,description})),vehicle:structuredClone(current),driver:order?structuredClone(latest.drivers.find(driver=>driver.id===order.driver_id)!):null,order:order?{...order}:null}};
 const nextVehicle={...current,mileage:d.mileage,location,site_id:site,parking_space_id:space,revision:(current.revision??1)+1,keys_revision:(current.keys_revision??1)+1,inventory_status:!order&&current.inventory_kind==='owned'?d.stock_status||null:current.inventory_status};
 let next:Data={...latest,vehicles:latest.vehicles.map(row=>row.id===v.id?nextVehicle:row),orders:latest.orders.map(o=>o.id===order?.id?{...o,status:kind==='pickup'?'in_transit':'completed',revision:(o.revision??1)+1}:o),handovers:[...latest.handovers,h],damages:[...latest.damages,...d.damages.map(damage=>({...damage,id:crypto.randomUUID(),organization_id:v.organization_id,vehicle_id:v.id,handover_id:h.id,created_at:now}))],events:[...latest.events,{id:crypto.randomUUID(),organization_id:v.organization_id,vehicle_id:v.id,order_id:order?.id??null,description:(kind==='pickup'?'Fahrzeugübernahme':'Fahrzeugübergabe')+(order?' '+order.reference:' · '+purposeLabels[d.purpose]),created_at:now}],keys:(latest.keys??[]).map(k=>selected.selected.some(s=>s.id===k.id)?{...k,state:(!order&&kind==='pickup')||(!!order&&kind==='delivery')?'available':'issued',location,custodian:(!order&&kind==='pickup')||(!!order&&kind==='delivery')?'':d.parties.receiver.name}:k),key_movements:[...(latest.key_movements??[]),...selected.selected.map(k=>({id:crypto.randomUUID(),organization_id:v.organization_id,vehicle_id:v.id,key_id:k.id,key_label:k.label,action:kind,person:d.parties.receiver.name,location,actor_name:latest.members[0]?.name??'Administrator',created_at:now,handover_id:h.id}))]};
 if(nextVehicle.inventory_status!==current.inventory_status)next={...next,stock_events:[...(next.stock_events??[]),{id:crypto.randomUUID(),organization_id:v.organization_id,vehicle_id:v.id,previous_kind:current.inventory_kind??'unassigned',next_kind:current.inventory_kind??'unassigned',previous_status:current.inventory_status??null,next_status:nextVehicle.inventory_status??null,reason:'Protokoll: '+purposeLabels[d.purpose],actor_name:latest.members[0]?.name??'Administrator',created_at:now,handover_id:h.id}]};
 return recordMovement(next,current,nextVehicle,order?kind:'manual',order?(kind==='pickup'?'Fahrzeugübernahme':'Fahrzeugübergabe')+' · '+order.reference:'Protokoll: '+purposeLabels[d.purpose],h.id);
 });
}
