import {Data,Handover,Vehicle} from './domain';
import {loadCloud,mutateDemo} from './repository';
import {supabase} from './supabase';
import {resolveDamagePhotos} from './damages';
export interface VehicleImage {id:string;kind:'protocol'|'asset';bucket:string;path:string;url?:string;label:string;created_at:string}
export function vehicleImages(data:Data,v:Vehicle):VehicleImage[]{return [...data.handovers.filter(h=>(h.vehicle_id??h.snapshot?.vehicle.id)===v.id).flatMap(h=>h.photos.map((p,i)=>({id:p.id??h.id+':'+i,kind:'protocol' as const,bucket:p.bucket??'evidence',path:p.path??'',url:p.url,label:(h.kind==='pickup'?'Übernahme':'Übergabe')+' · '+p.slot,created_at:h.created_at}))),...(data.assets??[]).filter(a=>a.vehicle_id===v.id&&a.kind==='photo').map(a=>({id:a.id,kind:'asset' as const,bucket:'vehicle-files',path:a.path,url:a.url,label:'Fahrzeugfoto · '+a.name,created_at:a.created_at}))].sort((a,b)=>b.created_at.localeCompare(a.created_at));}
export function coverImage(data:Data,v:Vehicle):VehicleImage|undefined{const images=vehicleImages(data,v),explicit=images.find(i=>i.id===v.cover_id&&i.kind===v.cover_kind);if(explicit)return explicit;const protocols=data.handovers.filter(h=>(h.vehicle_id??h.snapshot?.vehicle.id)===v.id).sort((a,b)=>b.created_at.localeCompare(a.created_at));const newest=protocols[0];if(newest){for(const slot of ['Vorne links','Vorne rechts','Vorne','Hinten links','Hinten rechts','Hinten','Links','Rechts']){const index=newest.photos.findIndex(p=>p.slot===slot);if(index>=0){const photo=newest.photos[index];return images.find(i=>i.id===(photo.id??newest.id+':'+index));}}}return images.find(i=>i.kind==='asset');}
export async function setCover(data:Data,v:Vehicle,image:VehicleImage|null,cloud:boolean){if(cloud){const r=await supabase!.rpc('set_vehicle_cover',{p_vehicle:v.id,p_revision:v.revision??1,p_kind:image?.kind as unknown as string??null as unknown as string,p_id:image?.id as unknown as string??null as unknown as string});if(r.error)throw Error(r.error.message);return(await loadCloud(data.organization.id))!;}return mutateDemo(latest=>{const old=latest.vehicles.find(row=>row.id===v.id);if(old?.revision!==v.revision)throw Error('Fahrzeug wurde inzwischen geändert.');return{...latest,vehicles:latest.vehicles.map(row=>row.id===v.id?{...row,cover_kind:image?.kind??null,cover_id:image?.id??null,revision:(row.revision??1)+1}:row)};});}
export async function resolveProtocol(h:Handover,cloud:boolean,damageDetails=false):Promise<Handover>{if(!cloud)return h;async function sign(bucket:string,path:string){if(!path)return '';const r=await supabase!.storage.from(bucket).createSignedUrl(path,300);if(r.error)throw Error(r.error.message);return r.data.signedUrl;}return {...h,snapshot:h.snapshot&&damageDetails?{...h.snapshot,known_damages:await resolveDamagePhotos(h.snapshot.known_damages??[],cloud),new_damages:h.snapshot.new_damages?await resolveDamagePhotos(h.snapshot.new_damages,cloud):undefined}:h.snapshot,signature:await sign(h.signature_bucket??'evidence',h.signature),photos:await Promise.all(h.photos.map(async p=>({...p,url:await sign(p.bucket??'evidence',p.path??'')}))),parties:h.parties?{...h.parties,giver:{...h.parties.giver,signature_url:await sign(h.signature_bucket??'protocol-media',h.parties.giver.signature)},receiver:{...h.parties.receiver,signature_url:await sign(h.signature_bucket??'protocol-media',h.parties.receiver.signature)}}:undefined};}
