import {test,expect,Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import sharp from 'sharp';
import {shots} from '../../src/lib/domain';
import {seed} from '../../src/lib/seed';
import {protocolSnapshot} from '../../src/lib/domain';
async function sign(page:Page,index:number){const canvas=page.getByLabel('Unterschrift mit Maus oder Finger zeichnen').nth(index);await canvas.scrollIntoViewIfNeeded();const b=(await canvas.boundingBox())!;await page.mouse.move(b.x+20,b.y+30);await page.mouse.down();await page.mouse.move(b.x+100,b.y+75,{steps:8});await page.mouse.move(b.x+170,b.y+35,{steps:8});await page.mouse.up();}
test('Unternehmensprofil, Logo, getrennte Teamansicht und Startbereich',async({page},info)=>{
 const png=await sharp({create:{width:180,height:60,channels:4,background:'#204bb4'}}).png().toBuffer();
 await page.goto('/');await page.getByRole('button',{name:'Organisation',exact:true}).click();await expect(page.getByRole('tab',{name:'Unternehmen'})).toHaveAttribute('aria-selected','true');await page.getByRole('button',{name:'Unternehmen bearbeiten'}).click();await page.getByLabel('Firmenname').fill('Autohaus Test');await page.getByLabel('Unternehmensart').selectOption('dealer');await page.getByLabel('Inhaber / Geschäftsführung').fill('Anna Test');await page.getByLabel('Straße und Hausnummer').fill('Testweg 12');await page.getByLabel('Postleitzahl').fill('10115');await page.getByLabel('Ort',{exact:true}).fill('Berlin');await page.getByLabel('Steuernummer',{exact:true}).fill('123-TEST');await page.getByLabel('Webseite').fill('https://example.com');await page.getByLabel('Unternehmenslogo').setInputFiles({name:'logo.png',mimeType:'image/png',buffer:png});await expect(page.getByAltText('Vorschau des neuen Unternehmenslogos')).toBeVisible();await page.getByRole('button',{name:'Unternehmen speichern'}).click();await expect(page.getByRole('heading',{name:'Autohaus Test'})).toBeVisible();await expect(page.getByText('123-TEST',{exact:true})).toBeVisible();await expect(page.locator('.company-panel').getByAltText('Logo Autohaus Test')).toBeVisible();await page.getByRole('tab',{name:'Team',exact:true}).click();await expect(page.getByLabel('Rolle für Alex Morgan')).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'3 von 3 Fahrzeugen'})).toBeVisible();await page.getByRole('button',{name:'Organisation',exact:true}).click();await page.screenshot({path:info.outputPath('company-profile.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);
 await page.getByRole('button',{name:'Unternehmen bearbeiten'}).click();await page.getByLabel('Aktuelles Logo entfernen').check();await page.getByLabel('Unternehmensart').selectOption('transfer');await page.getByRole('button',{name:'Unternehmen speichern'}).click();await expect(page.locator('.company-panel img')).toHaveCount(0);await page.reload();await expect(page.getByRole('heading',{name:'Aufträge',exact:true})).toBeVisible();
});
test('Fahrzeug ohne Kennzeichen, Baureihen und eigenständige Verkaufshistorie mit zwei Signaturen',async({page},info)=>{
 const jpeg=await sharp({create:{width:640,height:400,channels:3,background:'#446d85'}}).jpeg().toBuffer();
 await page.route('**/api/generations',route=>route.fulfill({json:{codes:['8P','8V','8VS'],source:'mobile.de',retrieved_at:'2026-10-02'}}));
 await page.goto('/');await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'Fahrzeug hinzufügen'}).click();await page.getByLabel('VIN',{exact:true}).fill('WAUZZZ8V0PE654321');await page.getByLabel('Hersteller',{exact:true}).fill('Audi');await page.getByRole('option',{name:'Audi',exact:true}).click();await page.getByLabel('Modell',{exact:true}).fill('A3');await page.getByRole('option',{name:'A3',exact:true}).click();await page.getByLabel('Erstzulassung (optional)').fill('2013-05-15');await page.getByRole('button',{name:'Baureihen zur Erstzulassung laden'}).click();await expect(page.getByRole('button',{name:'8VS',exact:true})).toBeVisible();await expect(page.getByLabel('Baureihe / Generation (optional)')).toHaveValue('');await page.getByRole('button',{name:'8V',exact:true}).click();await page.unroute('**/api/generations');await page.route('**/api/generations',route=>route.fulfill({status:503,json:{error:'Baureihenabfrage derzeit nicht verfügbar. Manuelle Eingabe bleibt möglich.'}}));await page.getByRole('button',{name:'Baureihen zur Erstzulassung laden'}).click();await expect(page.getByText('Baureihenabfrage derzeit nicht verfügbar. Manuelle Eingabe bleibt möglich.',{exact:true})).toBeVisible();await page.getByLabel('Baureihe / Generation (optional)').fill('8V');await page.getByLabel('Bestandszuordnung',{exact:true}).selectOption('owned');await page.getByLabel('Bestandsstatus',{exact:true}).selectOption('stock');await page.getByLabel('Farbe').fill('Blau');await page.getByLabel('Kilometerstand',{exact:true}).fill('100');await page.getByLabel('Standort',{exact:true}).fill('Verkaufshof');await page.getByRole('button',{name:'Speichern',exact:true}).click();await expect(page.getByRole('button',{name:'Audi A3 8V',exact:true})).toBeVisible();await page.getByRole('button',{name:'Audi A3 8V',exact:true}).click();await expect(page.getByText('Nicht zugeordnet',{exact:true})).toBeVisible();await expect(page.getByText('FZ-000004',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Übergabe am Fahrzeug',exact:true}).click();await page.getByLabel('Tank-/Ladestand (%)').fill('60');await page.getByLabel('Anlass',{exact:true}).selectOption('sale');await expect(page.getByLabel('Bestandsstatus nach Abschluss')).toHaveValue('sold');await page.getByLabel('Bestandsstatus bestätigt').check();await page.getByLabel('Tatsächliche Position',{exact:true}).fill('Beim Käufer');await page.getByLabel('Tatsächliche Position bestätigt').check();await page.getByLabel('Name der übernehmenden Person').fill('Max Käufer');await page.getByLabel('Transportkennzeichen (optional)').fill('B ROT 06');
 for(const shot of shots)await page.getByLabel('Foto '+shot,{exact:true}).setInputFiles({name:'car.jpg',mimeType:'image/jpeg',buffer:jpeg});await sign(page,0);await sign(page,1);await expect(page.getByRole('button',{name:'Protokoll abschließen'})).toBeEnabled();await page.getByLabel('Anmerkungen').fill('Winterräder mitgegeben');await expect(page.getByRole('button',{name:'Protokoll abschließen'})).toBeDisabled();await expect(page.getByText('Entwurf lokal gespeichert',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'Audi A3 8V',exact:true}).click();await page.getByRole('button',{name:'Übergabe am Fahrzeug',exact:true}).click();await page.getByLabel('Tank-/Ladestand (%)').fill('60');await expect(page.getByLabel('Anmerkungen')).toHaveValue('Winterräder mitgegeben');await expect(page.getByLabel('Name der übernehmenden Person')).toHaveValue('Max Käufer');await sign(page,0);await sign(page,1);await page.getByRole('button',{name:'Protokoll abschließen'}).click();await expect(page.getByRole('heading',{name:'Audi A3 8V'})).toBeVisible();await expect(page.locator('.history-row')).toContainText('Verkauft');await expect(page.locator('.current-position')).toContainText('Beim Käufer');await page.locator('.vehicle-gallery .large').scrollIntoViewIfNeeded();await expect(page.locator('.vehicle-gallery .large img')).toBeVisible();await expect(page.locator('.gallery-caption')).toContainText('Vorne links');await page.getByRole('button',{name:'Als Titelbild verwenden'}).click();await expect(page.getByRole('button',{name:'Automatisches Titelbild'})).toBeVisible();
 await page.getByRole('button',{name:'Ansehen',exact:true}).click();await expect(page.getByRole('dialog').getByText('Max Käufer · Ansprechpartner')).toBeVisible();await expect(page.getByRole('dialog').getByText('Im Bestand → Verkauft',{exact:true})).toBeVisible();await page.getByRole('dialog').screenshot({path:info.outputPath('new-protocol.png')});const event=page.waitForEvent('download');await page.getByRole('dialog').getByRole('button',{name:'PDF',exact:true}).click();const pdf=await event;await pdf.saveAs(info.outputPath('sale-protocol.pdf'));const bytes=(await readFile(info.outputPath('sale-protocol.pdf'))).toString('latin1');expect(bytes).toContain('FZ-000004');expect(bytes).toContain('B ROT 06');expect(bytes).toContain('Seite 1/');await page.getByRole('button',{name:'Protokoll schließen'}).click();
 await page.getByRole('button',{name:'Bestand',exact:true}).click();await page.getByLabel('Bestandsstatus filtern').selectOption('sold');await expect(page.getByRole('heading',{name:'1 von 4 Fahrzeugen'})).toBeVisible();await expect(page.getByRole('row').filter({hasText:'Audi A3 8V'})).toContainText('Ohne Transportauftrag');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await page.screenshot({path:info.outputPath('sold-inventory.png'),fullPage:true});
});
test('Unternehmensrevision verhindert Überschreiben aus einem zweiten Tab',async({page,context})=>{await page.goto('/');await page.getByRole('button',{name:'Organisation',exact:true}).click();await page.getByRole('button',{name:'Unternehmen bearbeiten'}).click();await page.getByLabel('Firmenname').fill('Veraltet');const second=await context.newPage();await second.goto('/');await second.getByRole('button',{name:'Organisation',exact:true}).click();await second.getByRole('button',{name:'Unternehmen bearbeiten'}).click();await second.getByLabel('Firmenname').fill('Neue Firma');await second.getByRole('button',{name:'Unternehmen speichern'}).click();await expect(second.getByRole('heading',{name:'Neue Firma'})).toBeVisible();await page.getByRole('button',{name:'Unternehmen speichern'}).click();await expect(page.locator('.company-panel').getByRole('alert')).toContainText('inzwischen geändert');});
test('Altes Ein-Signatur-Protokoll behält historischen PDF-Export',async({page})=>{
 const data=seed(),order=data.orders[0],snapshot=protocolSnapshot(data,order);snapshot.organization_name='Original Company';snapshot.order!.reference='LEGACY-1';const png=await sharp({create:{width:200,height:80,channels:4,background:'#204b77'}}).png().toBuffer(),jpeg=await sharp({create:{width:200,height:120,channels:3,background:'#477baa'}}).jpeg().toBuffer();data.organization.name='New Company';data.handovers.push({id:crypto.randomUUID(),organization_id:data.organization.id,order_id:order.id,kind:'pickup',mileage:data.vehicles[0].mileage,fuel:50,signer:'Original Signer',signature:'data:image/png;base64,'+png.toString('base64'),notes:'Original notes',photos:[{slot:'Vorne',url:'data:image/jpeg;base64,'+jpeg.toString('base64')}],created_at:new Date().toISOString(),snapshot});await page.goto('/');await expect(page.getByRole('button',{name:'Fahrzeuge',exact:true})).toBeVisible();await page.evaluate(async data=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('vehicleops-demo-v1',1);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});await new Promise<void>((resolve,reject)=>{const tx=db.transaction('data','readwrite');tx.objectStore('data').put(data,'state');tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();},data);await page.reload();await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'Volkswagen Golf Variant',exact:true}).click();await page.getByRole('button',{name:'Ansehen',exact:true}).click();await expect(page.getByRole('dialog').getByText('Ältere Protokollversion · eine Unterschrift')).toBeVisible();const event=page.waitForEvent('download');await page.getByRole('dialog').getByRole('button',{name:'PDF',exact:true}).click();const pdf=await event;expect(pdf.suggestedFilename()).toBe('LEGACY-1-Uebernahme.pdf');const content=(await readFile((await pdf.path())!)).toString('latin1');expect(content).toContain('Original Company');expect(content).toContain('Original Signer');expect(content).not.toContain('New Company');
});
test('Eine Signatur benötigt eine begründete Ausnahme; Ausnahmeänderung verlangt neue Bestätigung',async({page})=>{
 const jpeg=await sharp({create:{width:200,height:120,channels:3,background:'#477baa'}}).jpeg().toBuffer();await page.goto('/');await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'Volkswagen Golf Variant',exact:true}).click();await page.getByRole('button',{name:'Übernahme am Fahrzeug'}).click();await page.getByLabel('Tank-/Ladestand (%)').fill('60');await page.getByLabel('Name der übergebenden Person').fill('Lieferant');await page.getByLabel('Tatsächliche Position bestätigt').check();for(const shot of shots)await page.getByLabel('Foto '+shot,{exact:true}).setInputFiles({name:'car.jpg',mimeType:'image/jpeg',buffer:jpeg});await sign(page,0);await expect(page.getByRole('button',{name:'Protokoll abschließen'})).toBeDisabled();await page.getByLabel('Ausnahme: Eine Unterschrift kann nicht eingeholt werden').check();await page.getByLabel('Begründung für fehlende Unterschrift').fill('Person verweigert Unterschrift');await expect(page.getByRole('button',{name:'Protokoll abschließen'})).toBeDisabled();await sign(page,0);await expect(page.getByRole('button',{name:'Protokoll abschließen'})).toBeEnabled();await page.getByRole('button',{name:'Protokoll abschließen'}).click();await page.getByRole('button',{name:'Ansehen',exact:true}).click();await expect(page.getByRole('dialog').getByText('Ausnahme: Person verweigert Unterschrift')).toBeVisible();
});
