import {test,expect,Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import sharp from 'sharp';
import {shots} from '../../src/lib/domain';
async function open(page:Page){await page.goto('/');await page.getByRole('button',{name:'VO-2048',exact:true}).click();await page.getByRole('button',{name:'Übernahme starten',exact:true}).click();await expect(page.getByLabel('Tank-/Ladestand (%)')).toBeEnabled();}
async function sign(page:Page){for(const canvas of await page.getByLabel('Unterschrift mit Maus oder Finger zeichnen').all()){await canvas.scrollIntoViewIfNeeded();const b=(await canvas.boundingBox())!;await page.mouse.move(b.x+20,b.y+35);await page.mouse.down();await page.mouse.move(b.x+85,b.y+65,{steps:6});await page.mouse.move(b.x+140,b.y+30,{steps:6});await page.mouse.up();}}

test('Schadenmarkierung, mehrere Detailfotos, Entwurf, erneutes Signieren und eingefrorener PDF-Anhang',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const image=await sharp({create:{width:450,height:800,channels:3,background:'#bdc9d5'}}).jpeg().toBuffer(),file={name:'detail.jpg',mimeType:'image/jpeg',buffer:image};
 await open(page);await page.locator('.damage-zone-buttons').getByRole('button',{name:'Vorne links',exact:true}).click();await expect(page.getByLabel('Bereich Schaden 1')).toHaveValue('Vorne links');await page.getByLabel('Beschreibung Schaden 1').fill('Kratzer am Kotfluegel');
 await page.getByLabel('Detailfotos Schaden 1',{exact:true}).setInputFiles([file,{...file,name:'detail-2.jpg'}]);await expect(page.locator('.damage-edit-card img')).toHaveCount(2);await expect(page.getByText('0 / 10',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Detailfoto 1 von Schaden 1 entfernen',exact:true}).click();await expect(page.locator('.damage-edit-card img')).toHaveCount(1);await page.getByLabel('Detailfotos Schaden 1',{exact:true}).setInputFiles(file);await expect(page.locator('.damage-edit-card img')).toHaveCount(2);
 await page.waitForTimeout(650);await page.reload();await page.getByRole('button',{name:'VO-2048',exact:true}).click();await page.getByRole('button',{name:'Übernahme starten',exact:true}).click();await expect(page.getByLabel('Beschreibung Schaden 1')).toHaveValue('Kratzer am Kotfluegel');await expect(page.locator('.damage-edit-card img')).toHaveCount(2);await expect(page.getByRole('button',{name:'Neuer Schaden 1: Vorne links',exact:true}).first()).toBeVisible();
 await page.getByLabel('Tank-/Ladestand (%)').fill('60');await page.getByLabel('Name der übergebenden Person').fill('Autohaus');await page.getByLabel('Name der übernehmenden Person').fill('Fahrer');
 for(const slot of shots)await page.getByLabel('Foto '+slot,{exact:true}).setInputFiles(file);
 await sign(page);await expect(page.getByRole('button',{name:'Protokoll abschließen',exact:true})).toBeEnabled();await page.getByLabel('Beschreibung Schaden 1').fill('Kratzer am Kotfluegel, 4 cm');await expect(page.getByRole('button',{name:'Protokoll abschließen',exact:true})).toBeDisabled();await sign(page);
 await page.locator('section').filter({has:page.getByRole('heading',{name:'Schäden dokumentieren',exact:true})}).screenshot({path:info.outputPath('damage-editor.png')});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);
 await page.getByRole('button',{name:'Protokoll abschließen',exact:true}).click();await expect(page.getByRole('button',{name:'Übergabe starten',exact:true})).toBeVisible();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'PDF',exact:true}).click();const pdf=await download,path=info.outputPath('damage-protocol.pdf');await pdf.saveAs(path);const text=(await readFile(path)).toString('latin1');expect(text).toContain('Schadenfotos');expect(text).toContain('Schaden');expect(text).toContain('Kratzer am Kotfluegel, 4 cm');
 await page.getByRole('button',{name:'Übergabe starten',exact:true}).click();await expect(page.getByRole('button',{name:'Bekannter Schaden 1: Vorne links',exact:true}).first()).toBeVisible();await expect(page.locator('.damage-edit-card')).toHaveCount(0);await page.locator('.damage-cards summary').first().click();await expect(page.getByRole('link',{name:'Detailfoto 1: Vorne links öffnen'}).first()).toBeVisible();
 await page.getByRole('button',{name:'Zurück zum Auftrag',exact:false}).click();await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'Volkswagen Golf Variant',exact:true}).click();await page.locator('.vehicle-damages summary').click();await expect(page.locator('.vehicle-damages img')).toHaveCount(2);await page.locator('.vehicle-damages').screenshot({path:info.outputPath('vehicle-damages.png')});expect(errors).toEqual([]);
});

test('Bereich ohne Markierung, ungültige Datei und zugängliche Markierung lassen sich korrigieren',async({page})=>{
 await open(page);await page.locator('.damage-zone-buttons').getByRole('button',{name:'Innenraum',exact:true}).click();await expect(page.getByLabel('Bereich Schaden 1')).toHaveValue('Innenraum');await expect(page.getByRole('button',{name:'Neuer Schaden 1: Innenraum',exact:true})).toHaveCount(0);
 await page.getByLabel('Detailfotos Schaden 1',{exact:true}).setInputFiles({name:'bad.pdf',mimeType:'application/pdf',buffer:Buffer.from('bad')});await expect(page.locator('.damage-editor-layout').getByRole('alert')).toContainText('JPEG, PNG oder WebP');await expect(page.locator('.damage-edit-card img')).toHaveCount(0);
 await page.getByRole('button',{name:'Am Fahrzeug markieren',exact:true}).click();await page.locator('.damage-zone-buttons').getByRole('button',{name:'Hinten rechts',exact:true}).click();await expect(page.locator('.damage-edit-card')).toHaveCount(1);await expect(page.getByLabel('Bereich Schaden 1')).toHaveValue('Hinten rechts');await page.getByRole('button',{name:'Markierung entfernen',exact:true}).click();await expect(page.getByRole('button',{name:'Neuer Schaden 1: Hinten rechts',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Schaden 1 entfernen',exact:true}).click();await expect(page.locator('.damage-edit-card')).toHaveCount(0);
});
