import {test,expect,Page} from '@playwright/test';
async function setup(page:Page){await page.goto('/');await page.getByRole('button',{name:'Standorte',exact:true}).click();await page.getByLabel('Standortname').fill('Hof');await page.getByLabel('Stellplätze anlegen (optional)').selectOption('range');await page.getByLabel('Letzte Nummer').fill('3');await page.getByRole('button',{name:'Standort speichern',exact:true}).click();}
async function archiveSpace(page:Page){await page.getByRole('button',{name:'Stellplatz A-01 archivieren',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Archivieren bestätigen'}).click();await expect(page.locator('.space-row')).toHaveCount(2);}

test('Stellplatz- und Standortarchiv sind wiederherstellbar und neue Auswahlen enthalten nur aktive Bereiche',async({page},info)=>{
 await setup(page);await archiveSpace(page);const card=page.locator('.site-card');
 await card.getByRole('button',{name:'Archivierte Stellplätze anzeigen (1)'}).click();await expect(card.locator('.space-row')).toHaveCount(1);await expect(card.locator('.space-row')).toContainText('Archiviert');
 await card.getByRole('button',{name:'Stellplatz A-01 wiederherstellen',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Wiederherstellen',exact:true}).click();await card.getByRole('button',{name:'Aktive Stellplätze anzeigen'}).click();await expect(card.locator('.space-row')).toHaveCount(3);
 await archiveSpace(page);await page.getByRole('button',{name:'Standort Hof archivieren',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Archivieren bestätigen'}).click();await expect(page.locator('.site-card')).toHaveCount(0);
 await page.getByRole('button',{name:'Archivierte Standorte (1)',exact:true}).click();await expect(card.getByRole('heading',{name:'Hof',exact:true})).toBeVisible();await expect(card.getByRole('button',{name:'Mehrere Stellplätze anlegen',exact:true})).toHaveCount(0);await expect(card.locator('.space-row')).toHaveCount(3);
 await page.screenshot({path:info.outputPath('site-archive.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);
 await page.getByRole('button',{name:'Bestand',exact:true}).click();await expect(page.getByLabel('Standort filtern').getByRole('option',{name:'Hof',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Standorte',exact:true}).click();await page.getByRole('button',{name:'Archivierte Standorte (1)',exact:true}).click();await page.getByRole('button',{name:'Standort Hof wiederherstellen',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Wiederherstellen',exact:true}).click();await page.getByRole('button',{name:'Aktive Standorte (1)',exact:true}).click();await expect(card.locator('.space-row')).toHaveCount(2);
 await page.reload();await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'Volkswagen Golf Variant',exact:true}).click();await page.getByRole('button',{name:'Fahrzeug umsetzen',exact:true}).click();await page.getByLabel('Zielstandort',{exact:true}).selectOption({label:'Hof'});await expect(page.getByLabel('Zielstellplatz',{exact:true}).getByRole('option',{name:'A-01',exact:true})).toHaveCount(0);await expect(page.getByLabel('Zielstellplatz',{exact:true}).getByRole('option',{name:'A-02',exact:true})).toBeAttached();
});

test('Belegte Plätze führen zur Fahrzeugakte; geplante Transportziele bleiben gesperrt',async({page})=>{
 await setup(page);await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'Volkswagen Golf Variant',exact:true}).click();await page.getByRole('button',{name:'Fahrzeug umsetzen',exact:true}).click();await page.getByLabel('Zielstandort',{exact:true}).selectOption({label:'Hof'});await page.getByLabel('Zielstellplatz',{exact:true}).selectOption({label:'A-01'});await page.getByRole('button',{name:'Bewegung speichern',exact:true}).click();
 await page.getByRole('button',{name:'Standorte',exact:true}).click();await page.getByRole('button',{name:'Stellplatz A-01 archivieren',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('button',{name:'Archivieren bestätigen'})).toBeDisabled();await dialog.getByRole('button',{name:'Volkswagen Golf Variant ansehen und umsetzen'}).click();await expect(page.getByRole('heading',{name:'Volkswagen Golf Variant',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Fahrzeug umsetzen',exact:true}).click();await page.getByLabel('Zielstandort',{exact:true}).selectOption('');await page.getByLabel('Standortangabe',{exact:true}).fill('Werkstatt');await page.getByRole('button',{name:'Bewegung speichern',exact:true}).click();await page.getByRole('button',{name:'Übersicht',exact:true}).click();await page.getByRole('button',{name:'VO-2048',exact:true}).click();await page.getByRole('button',{name:'Auftrag bearbeiten'}).click();await page.getByLabel('Zielstandort',{exact:true}).selectOption({label:'Hof'});await page.getByLabel('Zielstellplatz (optional)').selectOption({label:'A-01'});await page.getByRole('button',{name:'Speichern',exact:true}).click();
 await page.getByRole('button',{name:'Standorte',exact:true}).click();await page.getByRole('button',{name:'Stellplatz A-01 archivieren',exact:true}).click();await expect(dialog.getByRole('button',{name:'Archivieren bestätigen'})).toBeDisabled();await dialog.getByRole('button',{name:'Auftrag VO-2048 ansehen'}).click();await expect(page.getByRole('button',{name:'Auftrag bearbeiten'})).toBeVisible();
});

test('Veraltete Archivierung überschreibt keine Änderung aus einem anderen Tab',async({page,context})=>{
 await setup(page);await page.getByRole('button',{name:'Standort Hof archivieren',exact:true}).click();
 const second=await context.newPage();await second.goto('/');await second.getByRole('button',{name:'Standorte',exact:true}).click();await second.getByRole('button',{name:'Standort Hof bearbeiten',exact:true}).click();await second.getByLabel('Standortname').fill('Hof neu');await second.getByRole('button',{name:'Standort speichern',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Archivieren bestätigen'}).click();await expect(page.getByRole('dialog').getByRole('alert')).toContainText('inzwischen geändert');await page.getByRole('dialog').getByRole('button',{name:'Abbrechen',exact:true}).click();await page.getByRole('button',{name:'Aktualisieren',exact:true}).click();await expect(page.getByRole('heading',{name:'Hof neu',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Standort Hof neu archivieren',exact:true}).click();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Standort Hof neu archivieren',exact:true})).toBeFocused();
});
