import {test,expect,Page} from '@playwright/test';
async function createSite(page:Page,name:string){await page.getByRole('button',{name:'Standorte',exact:true}).click();if(!await page.getByLabel('Standortname').isVisible())await page.getByRole('button',{name:'Standort hinzufügen',exact:true}).click();await page.getByLabel('Standortname').fill(name);await page.getByLabel('Standortanschrift').fill('Straße 1\n10115 Berlin');await page.getByRole('button',{name:'Standort speichern',exact:true}).click();await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();}
test('Standorte, Stellplätze, explizite Zuordnung und kombinierte Bestandsfilter',async({page},info)=>{
 await page.goto('/');await createSite(page,'Hof Berlin');const card=page.locator('.site-card').filter({has:page.getByRole('heading',{name:'Hof Berlin',exact:true})});await card.getByLabel('Stellplatz in Hof Berlin').fill('A-01');await card.getByRole('button',{name:'Stellplatz hinzufügen'}).click();await expect(card.locator('.space-row')).toContainText('A-01');await createSite(page,'Hof Hamburg');
 await page.getByRole('button',{name:'Bestand',exact:true}).click();await expect(page.getByRole('heading',{name:'3 von 3 Fahrzeugen'})).toBeVisible();await page.getByRole('button',{name:'Volkswagen Golf Variant',exact:true}).click();await expect(page.locator('.current-position')).toContainText('Berlin');await expect(page.locator('.movement-row')).toHaveCount(0);await page.getByRole('button',{name:'Fahrzeug umsetzen',exact:true}).click();await page.getByLabel('Zielstandort').selectOption({label:'Hof Berlin'});await page.getByLabel('Zielstellplatz').selectOption({label:'A-01'});await page.getByLabel('Anlass der Bewegung').fill('Anlieferung auf den Hof');await page.getByRole('button',{name:'Bewegung speichern'}).click();await expect(page.locator('.current-position')).toContainText('Hof Berlin · A-01');await expect(page.locator('.movement-row')).toHaveCount(1);await expect(page.locator('.movement-row')).toContainText('Anlieferung auf den Hof');
 await page.getByRole('button',{name:'Bestand',exact:true}).click();await page.getByLabel('Standort filtern').selectOption({label:'Hof Berlin'});await page.getByLabel('Stellplatz filtern').selectOption({label:'A-01'});await expect(page.getByRole('heading',{name:'1 von 3 Fahrzeugen'})).toBeVisible();await page.getByLabel('Verfügbarkeit',{exact:true}).selectOption('available');await expect(page.getByText('Keine Fahrzeuge für diese Filter.')).toBeVisible();await page.getByRole('button',{name:'Filter zurücksetzen'}).click();await page.getByLabel('Bestand durchsuchen').fill('golf');await expect(page.getByRole('button',{name:'Volkswagen Golf Variant',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'BMW 320d Touring',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Filter zurücksetzen'}).click();await page.screenshot({path:info.outputPath('inventory.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);
 await page.getByRole('button',{name:'BMW 320d Touring',exact:true}).click();await page.getByRole('button',{name:'Fahrzeug umsetzen'}).click();await page.getByLabel('Zielstandort').selectOption({label:'Hof Berlin'});await expect(page.getByRole('option',{name:'A-01 · belegt'})).toHaveAttribute('disabled','');await page.getByRole('button',{name:'Abbrechen',exact:true}).click();
 await page.getByRole('button',{name:'Standorte',exact:true}).click();await page.getByRole('button',{name:'Standort Hof Berlin bearbeiten',exact:true}).click();await page.getByLabel('Standortname').fill('Hof Mitte');await page.getByRole('button',{name:'Standort speichern',exact:true}).click();await expect(page.getByRole('heading',{name:'Hof Mitte',exact:true})).toBeVisible();await page.getByRole('button',{name:'Bestand',exact:true}).click();await page.getByRole('button',{name:'Volkswagen Golf Variant',exact:true}).click();await expect(page.locator('.current-position')).toContainText('Hof Mitte · A-01');await expect(page.locator('.movement-row')).toContainText('Hof Berlin · A-01');await expect(page.locator('.movement-row')).toHaveCount(1);await page.reload();await page.getByRole('button',{name:'Bestand',exact:true}).click();await page.getByRole('button',{name:'Volkswagen Golf Variant',exact:true}).click();await expect(page.locator('.current-position')).toContainText('Hof Mitte · A-01');await expect(page.locator('.movement-row')).toContainText('Anlieferung auf den Hof');
});
test('Gleichzeitige Standortänderungen überschreiben keine neueren Positionen',async({page,context})=>{
 await page.goto('/');await createSite(page,'Hof');await page.getByRole('button',{name:'Bestand',exact:true}).click();await page.getByRole('button',{name:'Volkswagen Golf Variant',exact:true}).click();await page.getByRole('button',{name:'Fahrzeug umsetzen'}).click();await page.getByLabel('Standortangabe',{exact:true}).fill('Werkstatt');await page.getByLabel('Anlass der Bewegung').fill('Veraltete Auswahl');
 const second=await context.newPage();await second.goto('/');await second.getByRole('button',{name:'Bestand',exact:true}).click();await second.getByRole('button',{name:'Volkswagen Golf Variant',exact:true}).click();await second.getByRole('button',{name:'Fahrzeug umsetzen'}).click();await second.getByLabel('Zielstandort').selectOption({label:'Hof'});await second.getByLabel('Anlass der Bewegung').fill('Aktuelle Position');await second.getByRole('button',{name:'Bewegung speichern'}).click();await expect(second.locator('.current-position')).toContainText('Hof');await page.getByRole('button',{name:'Bewegung speichern'}).click();await expect(page.locator('.vehicle-position').getByRole('alert')).toContainText('inzwischen geändert');await page.getByRole('button',{name:'Aktualisieren',exact:true}).click();await page.getByRole('button',{name:'Aktuelle Position übernehmen und neu prüfen'}).click();await page.getByRole('button',{name:'Abbrechen',exact:true}).click();await expect(page.locator('.current-position')).toContainText('Hof');await expect(page.locator('.movement-row')).toHaveCount(1);
});
