import {test,expect} from '@playwright/test';
const fresh={mobileAdId:'801',mobileSellerId:'55',vehicleClass:'Car',vin:'WAUZZZ8V0PE444333',make:'AUDI',model:'A3',mileage:12000,exteriorColor:'BLACK',firstRegistration:'202105',constructionYear:2020,internalNumber:'EXT-90'};
async function open(page:import('@playwright/test').Page){await page.goto('/');await page.getByRole('button',{name:'Organisation',exact:true}).click();await page.getByRole('tab',{name:'Anbindungen',exact:true}).click();await page.getByLabel('mobile.de-Händler-ID',{exact:true}).fill('55');}
async function upload(page:import('@playwright/test').Page,ads:unknown[]){await page.getByLabel('Seller-API-Importdatei').setInputFiles({name:'seller-ads.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({ads}))});await expect(page.getByRole('heading',{name:'Importvorschau'})).toBeVisible();}
test('Bestandsimport mit Vorschau, ausdrücklicher Zuordnung und wiederholter Datei',async({page},info)=>{
 await open(page);await upload(page,[fresh,{...fresh,mobileAdId:'802',vin:'WVWZZZ3CZPE123456',mileage:1,make:'VW',model:'GOLF'}]);
 await expect(page.getByText('Neu anlegen',{exact:true})).toBeVisible();await expect(page.getByText('VIN-Treffer',{exact:true})).toBeVisible();
 await page.getByLabel('Position der neuen Fahrzeuge').fill('Autohaus Berlin');await page.getByLabel('Bestandszuordnung für neue Fahrzeuge').selectOption('owned');await page.getByRole('button',{name:'Bis zu 100 Einträge auswählen'}).click();
 await page.getByRole('button',{name:'Ausgewählte Fahrzeuge übernehmen'}).click();await expect(page.getByRole('status')).toContainText('Import gespeichert');await expect(page.getByText(/1 neu · 1 zugeordnet/)).toBeVisible();
 await upload(page,[fresh,{...fresh,mobileAdId:'802',vin:'WVWZZZ3CZPE123456'}]);await expect(page.getByText('Bereits zugeordnet',{exact:true})).toHaveCount(2);await expect(page.getByRole('button',{name:'Ausgewählte Fahrzeuge übernehmen'})).toBeDisabled();
 await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await expect(page.locator('tbody tr')).toHaveCount(4);await page.getByRole('button',{name:'Volkswagen Golf Variant',exact:true}).click();await expect(page.getByText('28.450 km',{exact:true})).toBeVisible();await expect(page.locator('.current-position')).toContainText('Berlin');await page.getByRole('button',{name:'← Zurück zu Fahrzeugen',exact:true}).click();await page.getByRole('button',{name:'Audi A3',exact:true}).click();await expect(page.getByText('12.000 km',{exact:true})).toBeVisible();await expect(page.locator('.current-position')).toContainText('Autohaus Berlin');await page.getByRole('button',{name:'Fahrzeug bearbeiten'}).click();await expect(page.getByLabel('Ortskürzel',{exact:true})).toHaveValue('');await expect(page.getByLabel('Baujahr (optional)')).toHaveValue('2020');await expect(page.getByLabel('Erstzulassung (optional)')).toHaveValue('');await page.getByRole('button',{name:'Abbrechen',exact:true}).click();
 await page.getByRole('button',{name:'Organisation',exact:true}).click();await page.getByRole('tab',{name:'Anbindungen',exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await page.screenshot({path:info.outputPath('mobile-import.png'),fullPage:true});
});
test('Fehlende VIN ergänzen; Händlerabweichungen und doppelte VINs bleiben gesperrt',async({page})=>{
 await open(page);await upload(page,[{...fresh,vin:''},{...fresh,mobileAdId:'802',mobileSellerId:'56'}]);await expect(page.getByLabel('Inserat 801 auswählen')).toBeDisabled();await page.getByLabel('VIN für Inserat 801').fill('WAUZZZ8V0PE444334');await expect(page.getByLabel('Inserat 801 auswählen')).toBeEnabled();await expect(page.getByLabel('Inserat 802 auswählen')).toBeDisabled();await page.getByLabel('Position der neuen Fahrzeuge').fill('Hof Berlin');await page.getByLabel('Inserat 801 auswählen').check();await page.getByRole('button',{name:'Ausgewählte Fahrzeuge übernehmen'}).click();await expect(page.getByRole('status')).toContainText('Import gespeichert');
 await upload(page,[{...fresh,mobileAdId:'803'},{...fresh,mobileAdId:'804'}]);await expect(page.getByLabel('Inserat 803 auswählen')).toBeDisabled();await expect(page.getByLabel('Inserat 804 auswählen')).toBeDisabled();await expect(page.getByText('VIN mehrfach in der Vorschau.',{exact:true})).toHaveCount(2);
});
test('Veraltete Zuordnung verwirft auch vorherige Neuanlage; nach Aktualisierung erneut prüfen',async({page,context})=>{
 await open(page);await upload(page,[fresh,{...fresh,mobileAdId:'802',vin:'WVWZZZ3CZPE123456'}]);await page.getByLabel('Position der neuen Fahrzeuge').fill('Berlin');await page.getByRole('button',{name:'Bis zu 100 Einträge auswählen'}).click();
 const other=await context.newPage();await other.goto('/');await other.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await other.getByRole('button',{name:'Volkswagen Golf Variant',exact:true}).click();await other.getByRole('button',{name:'Fahrzeug bearbeiten'}).click();await other.getByLabel('Farbe',{exact:true}).fill('Neue Farbe');await other.getByRole('button',{name:'Speichern',exact:true}).click();
 await page.getByRole('button',{name:'Ausgewählte Fahrzeuge übernehmen'}).click();await expect(page.locator('.mobile-import').getByRole('alert')).toContainText('inzwischen geändert');await page.getByRole('button',{name:'Aktualisieren',exact:true}).click();await page.getByRole('button',{name:'Ausgewählte Fahrzeuge übernehmen'}).click();await expect(page.getByRole('status')).toContainText('Import gespeichert');await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await expect(page.locator('tbody tr')).toHaveCount(4);await expect(page.getByText('Neue Farbe',{exact:false})).toBeVisible();
});
