import {test,expect,Page} from '@playwright/test';
import sharp from 'sharp';
import {readFile} from 'node:fs/promises';
import {shots} from '../../src/lib/domain';
async function site(page:Page,name:string,bays:string[]){await page.getByRole('button',{name:'Standorte',exact:true}).click();if(!await page.getByLabel('Standortname').isVisible())await page.getByRole('button',{name:'Standort hinzufügen',exact:true}).click();await page.getByLabel('Standortname').fill(name);await page.getByLabel('Standortanschrift').fill(name+' Street 1, Berlin');await page.getByRole('button',{name:'Standort speichern',exact:true}).click();const card=page.locator('.site-card').filter({has:page.getByRole('heading',{name,exact:true})});for(const bay of bays){await card.getByLabel('Stellplatz in '+name).fill(bay);await card.getByRole('button',{name:'Stellplatz hinzufügen'}).click();await expect(card.locator('.space-row').filter({hasText:bay})).toBeVisible();}}
async function move(page:Page,car:string,site:string,bay:string){await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:car,exact:true}).click();await page.getByRole('button',{name:'Fahrzeug umsetzen',exact:true}).click();await page.getByLabel('Zielstandort',{exact:true}).selectOption({label:site});await page.getByLabel('Zielstellplatz',{exact:true}).selectOption({label:bay});await page.getByRole('button',{name:'Bewegung speichern',exact:true}).click();await expect(page.locator('.current-position')).toContainText(site+' · '+bay);}
async function evidence(page:Page,jpeg:Buffer){await page.getByLabel('Tank-/Ladestand (%)').fill('60');await page.getByLabel('Name der übergebenden Person').fill('Dealer');await page.getByLabel('Name der übernehmenden Person').fill('Driver');for(const slot of shots)await page.getByLabel('Foto '+slot,{exact:true}).setInputFiles({name:'car.jpg',mimeType:'image/jpeg',buffer:jpeg});}
async function sign(page:Page){for(const canvas of await page.getByLabel('Unterschrift mit Maus oder Finger zeichnen').all()){await canvas.scrollIntoViewIfNeeded();const b=(await canvas.boundingBox())!;await page.mouse.move(b.x+20,b.y+30);await page.mouse.down();await page.mouse.move(b.x+160,b.y+60,{steps:8});await page.mouse.up();}}
test('Standortroute, belegter Zielstellplatz, bestätigte Alternative und historisches PDF',async({page,context},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const jpeg=await sharp({create:{width:640,height:400,channels:3,background:'#406f92'}}).jpeg().toBuffer();
 await page.goto('/');await site(page,'Pickup Yard',['P1']);await site(page,'Destination Yard',['D1','D2']);await move(page,'Volkswagen Golf Variant','Pickup Yard','P1');
 await page.getByRole('button',{name:'Übersicht',exact:true}).click();await page.getByRole('button',{name:'VO-2048',exact:true}).click();await page.getByRole('button',{name:'Auftrag bearbeiten'}).click();await page.getByLabel('Abholstandort',{exact:true}).selectOption({label:'Pickup Yard'});await page.getByLabel('Zielstandort',{exact:true}).selectOption({label:'Destination Yard'});await page.getByLabel('Zielstellplatz (optional)',{exact:true}).selectOption({label:'D1'});await page.getByLabel('Ansprechpartner',{exact:true}).fill('Customer +49 151 12345678');await page.getByLabel('Transportkennzeichen (optional)').fill('B RED 07');await page.getByRole('button',{name:'Speichern',exact:true}).click();
 await expect(page.getByRole('link',{name:'Zur Abholung navigieren'})).toHaveAttribute('href',/Pickup%20Yard%20Street/);await expect(page.getByRole('link',{name:'Ansprechpartner anrufen'})).toHaveAttribute('href','tel:+4915112345678');await page.getByRole('button',{name:'Auftrag bearbeiten'}).click();await expect(page.getByLabel('Zielstellplatz (optional)')).toHaveValue(/.+/);await expect(page.getByLabel('Transportkennzeichen (optional)')).toHaveValue('B RED 07');await page.getByRole('button',{name:'Abbrechen',exact:true}).click();
 await page.getByRole('button',{name:'Übernahme starten'}).click();await expect(page.getByLabel('Tank-/Ladestand (%)')).toHaveValue('');await evidence(page,jpeg);await sign(page);await page.getByRole('button',{name:'Protokoll abschließen'}).click();await expect(page.getByRole('button',{name:'Übergabe starten'})).toBeVisible();
 await move(page,'BMW 320d Touring','Destination Yard','D1');await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'Volkswagen Golf Variant',exact:true}).click();await expect(page.locator('.current-position')).toContainText('In Transport');
 await page.getByRole('button',{name:'Übersicht',exact:true}).click();await page.getByRole('button',{name:'VO-2048',exact:true}).click();await expect(page.getByText('Der geplante Stellplatz ist belegt.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Übergabe starten'}).click();await expect(page.getByRole('option',{name:'D1 · belegt'})).toHaveAttribute('disabled','');await expect(page.getByLabel('Tatsächliche Position bestätigt')).not.toBeChecked();await page.getByLabel('Protokoll-Stellplatz').selectOption({label:'D2'});await page.getByLabel('Tatsächliche Position bestätigt').check();await evidence(page,jpeg);await sign(page);await expect(page.getByRole('button',{name:'Protokoll abschließen'})).toBeEnabled();
 // A position edit invalidates both signatures, even after confirmation.
 await page.getByLabel('Protokoll-Stellplatz').selectOption('');await expect(page.getByRole('button',{name:'Protokoll abschließen'})).toBeDisabled();await page.getByLabel('Protokoll-Stellplatz').selectOption({label:'D2'});await page.getByLabel('Tatsächliche Position bestätigt').check();await sign(page);await expect(page.getByText('Entwurf lokal gespeichert',{exact:true})).toBeVisible();const changedSite=await context.newPage();await changedSite.goto('/');await changedSite.getByRole('button',{name:'Standorte',exact:true}).click();await changedSite.getByRole('button',{name:'Standort Destination Yard bearbeiten',exact:true}).click();await changedSite.getByLabel('Standortname').fill('Renamed Yard');await changedSite.getByRole('button',{name:'Standort speichern',exact:true}).click();await expect(changedSite.getByRole('heading',{name:'Renamed Yard',exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'VO-2048',exact:true}).click();await page.getByRole('button',{name:'Übergabe starten'}).click();await expect(page.getByRole('button',{name:'Protokoll abschließen'})).toBeDisabled();await page.getByRole('button',{name:'Aktuellen Standort übernehmen und neu prüfen'}).click();await page.getByLabel('Tatsächliche Position bestätigt').check();await sign(page);await page.getByRole('button',{name:'Protokoll abschließen'}).click();await expect(page.getByText('Abgeschlossen',{exact:true})).toBeVisible();await changedSite.close();
 const downloadEvent=page.waitForEvent('download');await page.locator('.protocol-row').filter({has:page.getByText('Übergabe',{exact:true})}).getByRole('button',{name:'PDF',exact:true}).click();const download=await downloadEvent,text=(await readFile(await download.path())).toString('latin1');expect(text).toContain('Destination Yard');expect(text).toContain('Renamed Yard');expect(text).toContain('D2');expect(text).toContain('B RED 07');
 await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'Volkswagen Golf Variant',exact:true}).click();await expect(page.locator('.current-position')).toContainText('Renamed Yard · D2');await page.screenshot({path:info.outputPath('route-vehicle.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);expect(errors).toEqual([]);
});
test('Escape schließt zuerst den Katalog und danach das Fahrzeugformular',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'Fahrzeug hinzufügen'}).click();const maker=page.getByLabel('Hersteller',{exact:true});await maker.fill('Audi');await expect(maker).toHaveAttribute('aria-expanded','true');await maker.press('Escape');await expect(page.getByRole('dialog')).toBeVisible();await expect(maker).toHaveAttribute('aria-expanded','false');await maker.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);});
test('Veralteten Fahrzeugentwurf neu prüfen ohne Fotos zu verlieren',async({page,context})=>{
 const jpeg=await sharp({create:{width:200,height:120,channels:3,background:'#406f92'}}).jpeg().toBuffer();await page.goto('/');await page.getByRole('button',{name:'VO-2048',exact:true}).click();await page.getByRole('button',{name:'Übernahme starten'}).click();await evidence(page,jpeg);await sign(page);await expect(page.getByText('Entwurf lokal gespeichert',{exact:true})).toBeVisible();
 const second=await context.newPage();await second.goto('/');await second.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await second.getByRole('button',{name:'Volkswagen Golf Variant',exact:true}).click();await second.getByRole('button',{name:'Fahrzeug bearbeiten'}).click();await second.getByLabel('Farbe').fill('Grün');await second.getByRole('button',{name:'Speichern',exact:true}).click();await expect(second.getByRole('dialog')).toHaveCount(0);
 await page.reload();await page.getByRole('button',{name:'VO-2048',exact:true}).click();await page.getByRole('button',{name:'Übernahme starten'}).click();await expect(page.getByText('10 / 10',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Protokoll abschließen'})).toBeDisabled();await page.getByRole('button',{name:'Aktuelle Fahrzeugakte übernehmen und neu prüfen'}).click();await expect(page.getByText('10 / 10',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Protokoll abschließen'})).toBeDisabled();
 await expect.poll(()=>page.getByLabel('Unterschrift mit Maus oder Finger zeichnen').evaluateAll(canvases=>canvases.every(c=>{const canvas=c as HTMLCanvasElement,pixels=canvas.getContext('2d')!.getImageData(0,0,canvas.width,canvas.height).data;return !pixels.some((v,i)=>i%4===3&&v>0);}))).toBe(true);
 await sign(page);await page.getByRole('button',{name:'Protokoll abschließen'}).click();await expect(page.getByRole('button',{name:'Übergabe starten'})).toBeVisible();await second.close();
});
