import { test,expect } from '@playwright/test';
import sharp from 'sharp';
test('Fahrzeugakte, Anhänge, Schlüssel und unveränderliche Schlüsselhistorie',async({page},info)=>{
 const jpeg=await sharp({create:{width:120,height:80,channels:3,background:'#6699bb'}}).jpeg().toBuffer();
 await page.goto('/');await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'B NM 2048',exact:true}).click();await expect(page.getByText('Schlüsselbestand nicht erfasst',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Fahrzeug bearbeiten'}).click();await page.getByLabel('Baujahr (optional)').fill('2020');await page.getByLabel('Erstzulassung (optional)').fill('2021-02-03');await page.getByLabel('Name / Firma des Halters').fill('Testfirma');await page.getByLabel('Halteranschrift').fill('Teststraße 1\n10115 Berlin');await page.getByLabel('Halterkontakt (optional)').fill('test@example.com');await page.getByLabel('Fahrzeugfotos hinzufügen').setInputFiles([{name:'vorne.jpg',mimeType:'image/jpeg',buffer:jpeg},{name:'innen.jpg',mimeType:'image/jpeg',buffer:jpeg}]);await page.getByLabel('Fahrzeugschein hinzufügen').setInputFiles({name:'schein.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n%%EOF')});await page.getByRole('button',{name:'Speichern',exact:true}).click();await expect(page.getByText('Gespeichert',{exact:true})).toHaveCount(3);await expect(page.getByText('Testfirma',{exact:true})).toBeVisible();
 await page.getByLabel('Bezeichnung',{exact:true}).fill('Hauptschlüssel');await page.getByLabel('Kennung (optional)').fill('KEY-1');await page.getByLabel('Aufbewahrungsort',{exact:true}).fill('Schrank A');await page.getByRole('button',{name:'Schlüssel hinzufügen',exact:true}).click();await expect(page.getByText('1 erfasst · 1 vorhanden · 0 ausgegeben · 0 verloren',{exact:true})).toBeVisible();
 const card=page.locator('.key-card').filter({has:page.getByText('Hauptschlüssel',{exact:true})});await card.getByLabel('Person',{exact:true}).fill('Test Fahrer');await card.getByLabel('Neuer Aufbewahrungsort').fill('Beim Fahrer');await card.getByRole('button',{name:'Vorgang speichern'}).click();await expect(page.getByText('1 erfasst · 0 vorhanden · 1 ausgegeben · 0 verloren',{exact:true})).toBeVisible();await card.getByLabel('Vorgang').selectOption('return');await card.getByLabel('Neuer Aufbewahrungsort').fill('Schrank B');await card.getByRole('button',{name:'Vorgang speichern'}).click();await expect(page.getByText('1 erfasst · 1 vorhanden · 0 ausgegeben · 0 verloren',{exact:true})).toBeVisible();await card.getByRole('button',{name:'Bearbeiten',exact:true}).click();await page.getByLabel('Bezeichnung',{exact:true}).fill('Ersatzschlüssel');await page.getByRole('button',{name:'Schlüssel speichern',exact:true}).click();await expect(page.locator('.key-history').filter({hasText:'Erfasst · Hauptschlüssel'})).toBeVisible();
 const asset=page.locator('.asset-card').filter({has:page.getByText('vorne.jpg',{exact:true})});await asset.getByRole('button',{name:'Vorschau',exact:true}).click();await expect(asset.locator('img')).toBeVisible();await asset.getByRole('button',{name:'Entfernen',exact:true}).click();await page.getByRole('button',{name:'Datei entfernen',exact:true}).click();await expect(page.locator('.asset-card')).toHaveCount(2);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await page.screenshot({path:info.outputPath('vehicle-record.png'),fullPage:true});await page.reload();await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'B NM 2048',exact:true}).click();await expect(page.getByText('Testfirma',{exact:true})).toBeVisible();await expect(page.getByText('2020',{exact:true})).toBeVisible();await expect(page.locator('.asset-card')).toHaveCount(2);
});
test('Wiederherstellung ohne gültigen Link bietet keine Passwortänderung',async({page})=>{await page.goto('/auth/reset-password');await expect(page.getByRole('heading',{name:'Passwort zurücksetzen'})).toBeVisible();await expect(page.getByLabel('Neues Passwort',{exact:true})).toHaveCount(0);await expect(page.getByText('Passwort-Wiederherstellung benötigt den Cloud-Modus.')).toBeVisible();});
