import { test, expect } from '@playwright/test';
import { fillPlate } from './plate-helper';
test('Herstellerlogos, abhängige Modelle und Ausstattung bleiben nach Speichern erhalten',async({page},testInfo)=>{
 await page.goto('/');await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'Fahrzeug hinzufügen'}).click();
 await fillPlate(page,'B CAT 42');await page.getByLabel('VIN',{exact:true}).fill('WVWZZZ3CZPE999999');
 await expect(page.getByLabel('Modell',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'Hersteller-Liste öffnen'}).click();
 await page.getByLabel('Hersteller',{exact:true}).fill('Volks');const brand=page.getByRole('option',{name:'Volkswagen',exact:true});await expect(brand.locator('img')).toBeVisible();
 await page.getByRole('dialog').screenshot({path:testInfo.outputPath('manufacturer-picker.png')});await brand.click();
 await page.getByLabel('Modell',{exact:true}).fill('Golf');await page.getByRole('option',{name:'Golf',exact:true}).click();
 await page.getByLabel('Hersteller',{exact:true}).fill('BMW');await page.getByRole('option',{name:'BMW',exact:true}).click();await expect(page.getByLabel('Modell',{exact:true})).toHaveValue('');
 await page.getByRole('button',{name:'Modell-Liste öffnen'}).click();await expect(page.getByRole('option',{name:'Golf',exact:true})).toHaveCount(0);await page.getByLabel('Modell',{exact:true}).fill('320');await page.getByRole('option',{name:'320',exact:true}).click();
 await page.getByLabel('Ausführung / Variante (optional)').fill('Touring');await page.getByLabel('Farbe',{exact:true}).fill('Blau');await page.getByLabel('Kilometerstand',{exact:true}).fill('100');await page.getByLabel('Standort',{exact:true}).fill('Berlin');
 await page.getByLabel('Ausstattung suchen').fill('Sitzheizung');await page.getByLabel('Sitzheizung',{exact:true}).check();await page.getByLabel('Ausstattung suchen').fill('CarPlay');await page.getByLabel('Apple CarPlay',{exact:true}).check();await page.getByLabel('Ausstattung suchen').fill('');
 await expect(page.getByText('2 ausgewählt',{exact:true})).toBeVisible();await page.getByLabel('Zusätzliche Ausstattung (optional)').fill('Dachbox und Sonderumbau');await page.getByRole('dialog').screenshot({path:testInfo.outputPath('equipment-editor.png')});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);
 await page.getByRole('button',{name:'Speichern',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.reload();await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'BMW 320',exact:true}).click();
 await expect(page.getByText('Sitzheizung',{exact:true})).toBeVisible();await expect(page.getByText('Apple CarPlay',{exact:true})).toBeVisible();await expect(page.getByText('Ausführung: Touring',{exact:true})).toBeVisible();await expect(page.getByText('Dachbox und Sonderumbau',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Fahrzeug bearbeiten'}).click();await expect(page.getByLabel('Hersteller',{exact:true})).toHaveValue('BMW');await expect(page.getByLabel('Modell',{exact:true})).toHaveValue('320');await page.getByLabel('Ausstattung suchen').fill('Sitzheizung');await expect(page.getByLabel('Sitzheizung',{exact:true})).toBeChecked();await page.getByLabel('Sitzheizung',{exact:true}).uncheck();await page.getByRole('button',{name:'Speichern',exact:true}).click();await expect(page.getByText('Sitzheizung',{exact:true})).toHaveCount(0);await expect(page.getByText('Apple CarPlay',{exact:true})).toBeVisible();
});
test('VIN-Vorschläge werden erst nach Übernahme eingetragen; Fehler erlauben manuelle Eingabe',async({page,request})=>{
 expect((await request.post('/api/vin',{data:{vin:'short'}})).status()).toBe(400);
 await page.route('**/api/vin',route=>route.fulfill({json:{make:'Volkswagen',model:'Golf',year:'2020',message:'Hersteller und Modell erkannt. Bitte mit dem Fahrzeug abgleichen.'}}));
 await page.goto('/');await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'Fahrzeug hinzufügen'}).click();await page.getByLabel('VIN',{exact:true}).fill('WVWZZZ3CZPE123456');await page.getByRole('button',{name:'VIN prüfen',exact:true}).click();
 await expect(page.getByRole('button',{name:'Angaben übernehmen'})).toBeVisible();await expect(page.getByLabel('Hersteller',{exact:true})).toHaveValue('');await page.getByRole('button',{name:'Angaben übernehmen'}).click();await expect(page.getByLabel('Hersteller',{exact:true})).toHaveValue('Volkswagen');await expect(page.getByLabel('Modell',{exact:true})).toHaveValue('Golf');
 await page.unroute('**/api/vin');await page.route('**/api/vin',route=>route.fulfill({status:503,json:{error:'VIN-Erkennung ist gerade nicht verfügbar. Bitte manuell auswählen.'}}));await page.getByLabel('VIN',{exact:true}).fill('WBAZZZ3CZPE123456');await page.getByRole('button',{name:'VIN prüfen',exact:true}).click();await expect(page.locator('.vin-result')).toContainText('nicht verfügbar');await expect(page.getByLabel('Hersteller',{exact:true})).toHaveValue('Volkswagen');
 await page.getByLabel('Hersteller',{exact:true}).fill('Unbekannter Hersteller');await page.getByLabel('Modell',{exact:true}).fill('Sondermodell');await expect(page.getByLabel('Modell',{exact:true})).toHaveValue('Sondermodell');
});
test('Modellauswahl ist mit Tastatur bedienbar und erhält alte Modellnamen',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'Volkswagen Golf Variant',exact:true}).click();await page.getByRole('button',{name:'Fahrzeug bearbeiten'}).click();await expect(page.getByLabel('Modell',{exact:true})).toHaveValue('Golf Variant');
 await page.getByLabel('Hersteller',{exact:true}).fill('Audi');await page.getByLabel('Hersteller',{exact:true}).press('Enter');await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByLabel('Modell',{exact:true})).toHaveValue('');await page.getByLabel('Modell',{exact:true}).fill('A4');await page.getByLabel('Modell',{exact:true}).press('Enter');await expect(page.getByLabel('Modell',{exact:true})).toHaveValue('A4');await page.getByRole('button',{name:'Speichern',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
});

