// Isolated local Auth/Storage/Postgres only. Removes only its own fixtures.
import {execFileSync} from 'node:child_process';
import {createClient} from '@supabase/supabase-js';
import {chromium,devices,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import sharp from 'sharp';
const s=JSON.parse(execFileSync('npx.cmd',['supabase','status','--output','json'],{encoding:'utf8',shell:true,stdio:['ignore','pipe','pipe']}));
const admin=createClient(s.API_URL,s.SERVICE_ROLE_KEY,{auth:{persistSession:false}}),browser=await chromium.launch(),users=[],files=[];let org;
const ok=r=>{if(r.error)throw Error(r.error.message);return r.data;};
async function account(){const email='company-browser-'+crypto.randomUUID()+'@example.com',password=crypto.randomUUID()+'Aa1!';const user=ok(await admin.auth.admin.createUser({email,password,email_confirm:true})).user;users.push(user);const c=createClient(s.API_URL,s.PUBLISHABLE_KEY,{auth:{persistSession:false}});ok(await c.auth.signInWithPassword({email,password}));return{user,email,password,c};}
async function login(page,a){await page.goto('http://localhost:3000/');await page.getByLabel('E-Mail',{exact:true}).fill(a.email);await page.getByLabel('Passwort',{exact:true}).fill(a.password);await page.getByRole('button',{name:'Anmelden',exact:true}).click();await expect(page.getByRole('button',{name:'Organisation',exact:true})).toBeVisible();}
async function sign(page,index){const canvas=page.getByLabel('Unterschrift mit Maus oder Finger zeichnen').nth(index);await canvas.scrollIntoViewIfNeeded();const b=await canvas.boundingBox();await page.mouse.move(b.x+15,b.y+20);await page.mouse.down();await page.mouse.move(b.x+120,b.y+70,{steps:10});await page.mouse.up();}
try{
 const owner=await account(),viewer=await account(),other=await account();org=ok(await owner.c.rpc('create_organization',{p_name:'Company browser '+owner.user.id,p_member_name:'Owner'}));ok(await owner.c.rpc('add_member',{p_org:org,p_user:viewer.user.id,p_name:'Viewer',p_role:'viewer'}));const vehicle=crypto.randomUUID();ok(await owner.c.rpc('save_vehicle_record',{p_id:vehicle,p_org:org,p_revision:0,p_values:{plate:null,vin:'WAUZZZ8V0PE444333',make:'Audi',model:'A3',generation:'8V',inventory_kind:'owned',inventory_status:'stock',color:'Blue',mileage:100,location:'Dealer'},p_holder:null,p_holder_revision:0}));
 const mobile=await browser.newContext({...devices['Pixel 7']}),desktop=await browser.newContext(),p=await mobile.newPage(),v=await desktop.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));v.on('pageerror',e=>errors.push(e.message));await login(p,owner);await p.getByRole('button',{name:'Organisation',exact:true}).click();await p.getByRole('button',{name:'Unternehmen bearbeiten'}).click();await p.getByLabel('Firmenname').fill('Frozen Dealer');await p.getByLabel('Straße und Hausnummer').fill('Company Street 1');await p.getByLabel('Steuernummer').fill('TAX-2026');const logo=await sharp({create:{width:1400,height:500,channels:3,background:'#184dc6'}}).jpeg().toBuffer();await p.getByLabel('Unternehmenslogo').setInputFiles({name:'logo.jpg',mimeType:'image/jpeg',buffer:logo});await expect(p.getByAltText('Vorschau des neuen Unternehmenslogos')).toBeVisible();await p.getByRole('button',{name:'Unternehmen speichern'}).click();await expect(p.getByRole('heading',{name:'Frozen Dealer'})).toBeVisible();const orgRow=ok(await owner.c.from('organizations').select('*').eq('id',org).single());files.push(['company-logos',orgRow.logo_path]);const downloadLogo=ok(await owner.c.storage.from('company-logos').download(orgRow.logo_path));const metadata=await sharp(await downloadLogo.arrayBuffer()).metadata();expect(metadata.format).toBe('png');expect(metadata.width).toBeLessThanOrEqual(1024);
 const ownerToken=(await owner.c.auth.getSession()).data.session.access_token,viewerToken=(await viewer.c.auth.getSession()).data.session.access_token,otherToken=(await other.c.auth.getSession()).data.session.access_token;
 const uploadEndpoint='http://localhost:3000/api/company-logo';expect((await p.request.post(uploadEndpoint,{multipart:{organization_id:org,logo:{name:'fake.png',mimeType:'image/png',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"><rect width="10" height="10"/></svg>')}},headers:{Authorization:'Bearer '+ownerToken}})).status()).toBe(400);expect((await p.request.post(uploadEndpoint,{multipart:{organization_id:org,logo:{name:'logo.jpg',mimeType:'image/jpeg',buffer:logo}},headers:{Authorization:'Bearer '+viewerToken}})).status()).toBe(403);
 await p.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await p.getByRole('button',{name:'Audi A3 8V',exact:true}).click();await p.getByRole('button',{name:'Übergabe am Fahrzeug'}).click();await p.getByLabel('Tank-/Ladestand (%)').fill('60');await p.getByLabel('Anlass',{exact:true}).selectOption('rental');await p.getByLabel('Bestandsstatus bestätigt').check();await p.getByLabel('Tatsächliche Position',{exact:true}).fill('Rental customer');await p.getByLabel('Tatsächliche Position bestätigt').check();await p.getByLabel('Name der übernehmenden Person').fill('Rental Customer');const jpeg=await sharp({create:{width:1600,height:900,channels:3,background:'#476d9b'}}).jpeg().toBuffer();for(const slot of['Vorne','Hinten','Links','Rechts','Vorne links','Vorne rechts','Hinten links','Hinten rechts','Innenraum','Tacho'])await p.getByLabel('Foto '+slot,{exact:true}).setInputFiles({name:'car.jpg',mimeType:'image/jpeg',buffer:jpeg});await sign(p,0);await sign(p,1);await p.getByRole('button',{name:'Protokoll abschließen'}).click();await expect(p.getByRole('heading',{name:'Audi A3 8V'})).toBeVisible({timeout:30000});await p.locator('.vehicle-gallery .large').scrollIntoViewIfNeeded();await expect(p.locator('.vehicle-gallery .large img')).toBeVisible();await expect(p.locator('.gallery-caption')).toContainText('Vorne links');await p.getByRole('button',{name:'Als Titelbild verwenden'}).click();await expect(p.getByRole('button',{name:'Automatisches Titelbild'})).toBeVisible();
 const h=ok(await owner.c.from('handovers').select('*').eq('vehicle_id',vehicle).single());expect(h.order_id).toBe(null);expect(h.position.stock_status).toBe('rented');expect(h.snapshot.organization.logo_path).toBe(orgRow.logo_path);const photo=ok(await owner.c.from('handover_photos').select('*').eq('handover_id',h.id).eq('slot','Vorne links').single());const imageEndpoint='http://localhost:3000/api/vehicle-image',body={organization_id:org,bucket:'protocol-media',path:photo.path};expect((await p.request.post(imageEndpoint,{data:body})).status()).toBe(401);expect((await p.request.post(imageEndpoint,{data:body,headers:{Authorization:'Bearer '+otherToken}})).status()).toBe(403);expect((await p.request.post(imageEndpoint,{data:{...body,path:h.signature},headers:{Authorization:'Bearer '+ownerToken}})).status()).toBe(403);const thumbnail=await p.request.post(imageEndpoint,{data:body,headers:{Authorization:'Bearer '+viewerToken}});expect(thumbnail.status()).toBe(200);const thumb=await sharp(await thumbnail.body()).metadata();expect(thumb.width).toBeLessThanOrEqual(320);expect(thumb.height).toBeLessThanOrEqual(240);
 await p.getByRole('button',{name:'Organisation',exact:true}).click();await p.getByRole('button',{name:'Unternehmen bearbeiten'}).click();await p.getByLabel('Firmenname').fill('Changed company');await p.getByLabel('Aktuelles Logo entfernen').check();await p.getByLabel('Steuernummer').fill('NEW-TAX');await p.getByRole('button',{name:'Unternehmen speichern'}).click();await expect(p.getByRole('heading',{name:'Changed company'})).toBeVisible();
 await login(v,viewer);await v.getByRole('button',{name:'Organisation',exact:true}).click();await expect(v.getByRole('button',{name:'Unternehmen bearbeiten'})).toHaveCount(0);await v.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await expect(v.locator('.vehicle-photo img')).toBeVisible();await v.getByRole('button',{name:'Audi A3 8V',exact:true}).click();await expect(v.getByRole('button',{name:'Übergabe am Fahrzeug'})).toHaveCount(0);await expect(v.getByRole('button',{name:'Als Titelbild verwenden'})).toHaveCount(0);await v.getByRole('button',{name:'Ansehen',exact:true}).click();await expect(v.getByRole('dialog').getByText('Frozen Dealer',{exact:true})).toBeVisible();await expect(v.getByRole('dialog').getByAltText('Logo Frozen Dealer')).toBeVisible();const event=v.waitForEvent('download');await v.getByRole('dialog').getByRole('button',{name:'PDF',exact:true}).click();const pdf=await event;const bytes=(await readFile(await pdf.path())).toString('latin1');expect(bytes).toContain('Frozen Dealer');expect(bytes).toContain('TAX-2026');expect(bytes).not.toContain('NEW-TAX');expect(bytes).not.toContain('Changed company');await pdf.saveAs('docs/company-protocol-sample.pdf');await v.getByRole('dialog').screenshot({path:'docs/company-protocol-desktop.png'});await p.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await p.getByRole('button',{name:'Audi A3 8V',exact:true}).click();await p.locator('.vehicle-gallery .large').scrollIntoViewIfNeeded();await expect(p.locator('.vehicle-gallery .large img')).toBeVisible();await p.screenshot({path:'docs/company-vehicle-mobile.png',fullPage:true});expect(await p.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);expect(errors).toEqual([]);
 console.log('PASS: real mobile company logo normalization, spoofed SVG rejection, role access, standalone rental, private resized thumbnails, manual cover, desktop viewer, frozen company/logo PDF and mobile layout');
}finally{
 await browser.close();if(org){const sessions=ok(await admin.from('protocol_sessions').select('id').eq('organization_id',org));for(const session of sessions){const rows=ok(await admin.storage.from('protocol-media').list(org+'/'+session.id));files.push(...rows.map(f=>['protocol-media',org+'/'+session.id+'/'+f.name]));}for(const table of['stock_events','protocol_sessions','key_movements','vehicle_movements','handover_photos','damages','handovers','vehicle_keys','vehicle_assets','vehicle_holders','vehicle_events','orders','drivers','vehicles','memberships'])ok(await admin.from(table).delete().eq('organization_id',org));ok(await admin.from('organizations').delete().eq('id',org));}for(const[bucket,path]of files)ok(await admin.storage.from(bucket).remove([path]));for(const user of users)ok(await admin.auth.admin.deleteUser(user.id));
}
