import {execFileSync} from 'node:child_process';
import {readFile} from 'node:fs/promises';
import {createClient} from '@supabase/supabase-js';
import {chromium,devices,expect} from '@playwright/test';
import sharp from 'sharp';
const config=JSON.parse(execFileSync(process.platform==='win32'?'npx.cmd':'npx',['supabase','status','--output','json'],{encoding:'utf8',shell:process.platform==='win32',stdio:['ignore','pipe','pipe']}));
const admin=createClient(config.API_URL,config.SERVICE_ROLE_KEY,{auth:{persistSession:false}}),users=[],orgs=[],browser=await chromium.launch();
const ok=r=>{if(r.error)throw Error(r.error.message);return r.data;};
async function account(){const email='damages-browser-'+crypto.randomUUID()+'@example.com',password=crypto.randomUUID()+'Aa1!',user=ok(await admin.auth.admin.createUser({email,password,email_confirm:true})).user;users.push(user);return{email,password,user};}
async function login(page,a){await page.goto('http://localhost:3000/');await page.getByLabel('E-Mail',{exact:true}).fill(a.email);await page.getByLabel('Passwort',{exact:true}).fill(a.password);await page.getByRole('button',{name:'Anmelden',exact:true}).click();}
async function sign(page){for(const canvas of await page.getByLabel('Unterschrift mit Maus oder Finger zeichnen').all()){await canvas.scrollIntoViewIfNeeded();const b=await canvas.boundingBox();await page.mouse.move(b.x+20,b.y+35);await page.mouse.down();await page.mouse.move(b.x+85,b.y+65,{steps:6});await page.mouse.move(b.x+140,b.y+30,{steps:6});await page.mouse.up();}}
try{
 for(const device of['desktop','mobile']){
  const owner=await account(),viewer=await account(),c=createClient(config.API_URL,config.PUBLISHABLE_KEY,{auth:{persistSession:false}});ok(await c.auth.signInWithPassword({email:owner.email,password:owner.password}));const org=ok(await c.rpc('create_organization',{p_name:'Damage Browser '+device,p_member_name:'Owner'}));orgs.push(org);ok(await c.rpc('add_member',{p_org:org,p_user:viewer.user.id,p_name:'Viewer',p_role:'viewer'}));const vehicle=crypto.randomUUID();ok(await c.rpc('save_vehicle_record',{p_id:vehicle,p_org:org,p_revision:0,p_values:{plate:null,vin:'WVWZZZ3CZPE123456',make:'Volkswagen',model:'Golf',color:'Blau',mileage:100,location:'Hof'},p_holder:null,p_holder_revision:0}));
  const context=await browser.newContext(device==='mobile'?devices['Pixel 7']:{}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await login(page,owner);await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'Volkswagen Golf',exact:true}).click();await page.getByRole('button',{name:'Übernahme am Fahrzeug',exact:true}).click();
  await page.locator('.damage-zone-buttons').getByRole('button',{name:'Vorne rechts',exact:true}).click();await page.getByLabel('Beschreibung Schaden 1').fill('Kratzer an der Haube');const bytes=await sharp({create:{width:500,height:700,channels:3,background:'#abc'}}).jpeg().toBuffer(),photo={name:'damage.jpg',mimeType:'image/jpeg',buffer:bytes};
  await page.getByLabel('Detailfotos Schaden 1',{exact:true}).setInputFiles([photo,{...photo,name:'detail.jpg'}]);await expect(page.locator('.damage-edit-card img')).toHaveCount(2);await page.getByLabel('Tank-/Ladestand (%)').fill('50');await page.getByLabel('Name der übergebenden Person').fill('Kunde');await page.getByLabel('Name der übernehmenden Person').fill('Autohaus');await page.getByLabel('Tatsächliche Position bestätigt').check();
  for(const slot of['Vorne','Hinten','Links','Rechts','Vorne links','Vorne rechts','Hinten links','Hinten rechts','Innenraum','Tacho'])await page.getByLabel('Foto '+slot,{exact:true}).setInputFiles(photo);await sign(page);
  let lost=true;await page.route('**/rest/v1/rpc/finalize_protocol',async route=>{if(lost){lost=false;const response=await route.fetch();expect(response.ok()).toBe(true);await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'Abschlussantwort verloren. Bitte erneut versuchen.'})});}else await route.continue();});
  await page.getByRole('button',{name:'Protokoll abschließen',exact:true}).click();await expect(page.locator('.inspection').getByRole('alert')).toContainText('Abschlussantwort verloren');expect(ok(await admin.from('damages').select('id').eq('vehicle_id',vehicle))).toHaveLength(1);expect(ok(await admin.from('damage_photos').select('id').eq('organization_id',org))).toHaveLength(2);
  await page.getByRole('button',{name:'Protokoll abschließen',exact:true}).click();await expect(page.getByRole('heading',{name:'Volkswagen Golf',exact:true})).toBeVisible();expect(ok(await admin.from('handovers').select('id').eq('vehicle_id',vehicle))).toHaveLength(1);await page.locator('.vehicle-damages summary').click();await expect(page.locator('.vehicle-damages img')).toHaveCount(2);for(const image of await page.locator('.vehicle-damages img').all())await expect.poll(()=>image.evaluate(img=>img.complete&&img.naturalWidth>0)).toBe(true);
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'PDF',exact:true}).click();const pdf=await download;expect((await readFile(await pdf.path())).toString('latin1')).toContain('Schadenfotos');
  await page.reload();await page.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await page.getByRole('button',{name:'Volkswagen Golf',exact:true}).click();await page.locator('.vehicle-damages summary').click();await expect(page.locator('.vehicle-damages img')).toHaveCount(2);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);expect(errors).toEqual([]);
  const readContext=await browser.newContext(),read=await readContext.newPage();await login(read,viewer);await read.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await read.getByRole('button',{name:'Volkswagen Golf',exact:true}).click();await read.locator('.vehicle-damages summary').click();await expect(read.locator('.vehicle-damages img')).toHaveCount(2);await expect(read.getByRole('button',{name:'Übernahme am Fahrzeug',exact:true})).toHaveCount(0);await readContext.close();await context.close();
 }
 console.log('PASS: real desktop/mobile damage capture, normalized uploads and private previews, lost completion response retry without duplicates, reload and viewer read-only gallery');
}finally{
 await browser.close();for(const org of orgs){const list=ok(await admin.storage.from('protocol-media').list(org));for(const folder of list){const children=ok(await admin.storage.from('protocol-media').list(org+'/'+folder.name));if(children.length)ok(await admin.storage.from('protocol-media').remove(children.map(file=>org+'/'+folder.name+'/'+file.name)));}for(const table of['stock_events','protocol_sessions','key_movements','vehicle_movements','handover_photos','damages','handovers','vehicle_keys','vehicle_assets','vehicle_holders','vehicle_events','orders','drivers','vehicles','memberships'])ok(await admin.from(table).delete().eq('organization_id',org));ok(await admin.from('organizations').delete().eq('id',org));}for(const user of users)ok(await admin.auth.admin.deleteUser(user.id));
}
