// Real local cloud UI for fixed sites, bays, movement history and read-only team access.
import {execFileSync} from 'node:child_process';
import {createClient} from '@supabase/supabase-js';
import {chromium,devices,expect} from '@playwright/test';
const s=JSON.parse(execFileSync(process.platform==='win32'?'npx.cmd':'npx',['supabase','status','--output','json'],{encoding:'utf8',shell:process.platform==='win32',stdio:['ignore','pipe','pipe']}));
const admin=createClient(s.API_URL,s.SERVICE_ROLE_KEY,{auth:{persistSession:false}}),accounts=[],browser=await chromium.launch();let org;
const ok=r=>{if(r.error)throw Error(r.error.message);return r.data;};
async function account(){const email='inventory-browser-'+crypto.randomUUID()+'@example.com',password=crypto.randomUUID()+'Aa1!';const user=ok(await admin.auth.admin.createUser({email,password,email_confirm:true})).user;accounts.push(user);return{email,password,user};}
async function login(page,a){await page.goto('http://localhost:3000/');await page.getByLabel('E-Mail',{exact:true}).fill(a.email);await page.getByLabel('Passwort',{exact:true}).fill(a.password);await page.getByRole('button',{name:'Anmelden',exact:true}).click();await expect(page.getByRole('heading',{name:'Alles bereit für die nächste Fahrt.'})).toBeVisible();}
try{
 const a=await account(),viewer=await account(),c=createClient(s.API_URL,s.PUBLISHABLE_KEY,{auth:{persistSession:false}});ok(await c.auth.signInWithPassword({email:a.email,password:a.password}));org=ok(await c.rpc('create_organization',{p_name:'Inventory browser '+a.user.id,p_member_name:'Inventory Owner'}));ok(await c.rpc('add_member',{p_org:org,p_user:viewer.user.id,p_name:'Viewer',p_role:'viewer'}));const vehicle=crypto.randomUUID();ok(await c.from('vehicles').insert({id:vehicle,organization_id:org,plate:'B INV 1',vin:'WVWZZZ3CZPE999777',make:'VW',model:'Golf',color:'Blue',mileage:100,location:'Berlin'}));
 const ownerContext=await browser.newContext({...devices['Pixel 7']}),readContext=await browser.newContext(),p=await ownerContext.newPage(),v=await readContext.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));v.on('pageerror',e=>errors.push(e.message));await login(p,a);await p.getByRole('button',{name:'Standorte',exact:true}).click();await p.getByLabel('Standortname').fill('Cloud Hof');await p.getByLabel('Standortanschrift').fill('Teststraße 1');await p.getByRole('button',{name:'Standort speichern'}).click();const card=p.locator('.site-card');await card.getByLabel('Stellplatz in Cloud Hof').fill('C-01');await card.getByRole('button',{name:'Stellplatz hinzufügen'}).click();await expect(card.locator('.space-row')).toContainText('C-01');
 await p.getByRole('button',{name:'Bestand',exact:true}).click();await p.getByRole('button',{name:'VW Golf',exact:true}).click();await p.getByRole('button',{name:'Fahrzeug umsetzen'}).click();await p.getByLabel('Zielstandort').selectOption({label:'Cloud Hof'});await p.getByLabel('Zielstellplatz').selectOption({label:'C-01'});await p.getByLabel('Anlass der Bewegung').fill('Cloud Anlieferung');await p.getByRole('button',{name:'Bewegung speichern'}).click();await expect(p.locator('.current-position')).toContainText('Cloud Hof · C-01');expect(ok(await c.from('vehicles').select('parking_space_id').eq('id',vehicle).single()).parking_space_id).toBeTruthy();
 await login(v,viewer);await v.getByRole('button',{name:'Bestand',exact:true}).click();await expect(v.getByRole('button',{name:'Fahrzeug hinzufügen'})).toHaveCount(0);await v.getByRole('button',{name:'VW Golf',exact:true}).click();await expect(v.locator('.current-position')).toContainText('Cloud Hof · C-01');await expect(v.getByRole('button',{name:'Fahrzeug umsetzen'})).toHaveCount(0);await v.getByRole('button',{name:'Standorte',exact:true}).click();await expect(v.getByRole('heading',{name:'Cloud Hof',exact:true})).toBeVisible();await expect(v.getByRole('button',{name:'Standort hinzufügen'})).toHaveCount(0);await expect(v.getByRole('button',{name:'Bearbeiten',exact:true})).toHaveCount(0);
 await p.getByRole('button',{name:'Fahrzeug umsetzen'}).click();await p.getByLabel('Zielstandort').selectOption('');await p.getByLabel('Standortangabe',{exact:true}).fill('Werkstatt');await p.getByLabel('Anlass der Bewegung').fill('Reparatur');await p.getByRole('button',{name:'Bewegung speichern'}).click();await expect(p.locator('.current-position')).toContainText('Werkstatt');const moved=ok(await c.from('vehicles').select('site_id,parking_space_id').eq('id',vehicle).single());expect(moved).toEqual({site_id:null,parking_space_id:null});expect(ok(await c.from('vehicle_movements').select('*').eq('vehicle_id',vehicle))).toHaveLength(3);await p.getByRole('button',{name:'Bestand',exact:true}).click();await p.getByLabel('Standort filtern').selectOption('unassigned');await expect(p.getByRole('button',{name:'VW Golf',exact:true})).toBeVisible();expect(await p.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);expect(errors).toEqual([]);
 console.log('PASS: mobile real cloud site/bay creation, structured and free-location movement, durable history, stock filters and desktop viewer read-only UI');
}finally{await browser.close();if(org){for(const table of ['vehicle_movements','vehicle_events','vehicles','parking_spaces','fleet_sites','memberships'])ok(await admin.from(table).delete().eq('organization_id',org));ok(await admin.from('organizations').delete().eq('id',org));}for(const a of accounts)ok(await admin.auth.admin.deleteUser(a.id));}
