import {describe,it,expect} from 'vitest';
import {seed} from '../src/lib/seed';
import {filterInventory,inventoryState,moveInventory,positionLabel} from '../src/lib/inventory-domain';
function fixture(){const data=seed(),org=data.organization.id;data.sites=[{id:'site',organization_id:org,name:'Hof Berlin',address:'Straße 1',revision:1}];data.spaces=[{id:'bay',organization_id:org,site_id:'site',label:'A-01',revision:1}];return data;}
describe('Bestand und Fahrzeugposition',()=>{
 it('alte Angaben bleiben ohne erfundene Standortzuordnung und Historie erhalten',()=>{const d=fixture();expect(positionLabel(d,d.vehicles[0])).toBe('Berlin');expect(d.vehicles[0].site_id).toBeUndefined();expect(d.movements).toBeUndefined();expect(inventoryState(d,d.vehicles[0])).toBe('reserved');expect(inventoryState(d,d.vehicles[2])).toBe('available');});
 it('belegte Plätze, fremde Plätze, fehlende Gründe und veraltete Änderungen scheitern',()=>{const d=fixture(),v=d.vehicles[0],moved=moveInventory(d,v,'site','bay','','Zuordnung');expect(()=>moveInventory(moved,moved.vehicles[1],'site','bay','','Parken')).toThrow('belegt');expect(()=>moveInventory(d,v,'site','foreign','','Parken')).toThrow('nicht zum Standort');expect(()=>moveInventory(d,v,'foreign',null,'','Parken')).toThrow('nicht zum Arbeitsbereich');expect(()=>moveInventory(d,v,'site',null,'',' ')).toThrow('Anlass');expect(()=>moveInventory(moved,v,'site',null,'','Umsetzen')).toThrow('inzwischen');expect(()=>moveInventory(moved,moved.vehicles[0],'site','bay','','Umsetzen')).toThrow('bereits');});
 it('Bewegungen halten damalige Bezeichnungen fest und lassen keine manuelle Änderung im Transport zu',()=>{let d=fixture();d=moveInventory(d,d.vehicles[0],'site','bay','','Anlieferung');expect(d.movements![0]).toMatchObject({from_location:'Berlin',to_location:'Hof Berlin · A-01',reason:'Anlieferung',actor_name:'Alex Morgan'});d.sites![0].name='Neuer Hof';expect(d.movements![0].to_location).toBe('Hof Berlin · A-01');d.orders[0].status='in_transit';expect(()=>moveInventory(d,d.vehicles[0],null,null,'Hamburg','Transport')).toThrow('in Transport');});
 it('Standort, Stellplatz, Verfügbarkeit, Transport und Suche können kombiniert werden',()=>{let d=fixture();d=moveInventory(d,d.vehicles[0],'site','bay','','Anlieferung');const filters={search:'golf',site:'site',space:'bay',availability:'allocated',transport:'stationary'};expect(filterInventory(d,filters).map(v=>v.plate)).toEqual(['B NM 2048']);expect(filterInventory(d,{...filters,availability:'available'})).toEqual([]);expect(filterInventory(d,{search:'',site:'unassigned',space:'',availability:'available',transport:''}).map(v=>v.plate)).toEqual(['H NM 340']);d.orders[0].status='in_transit';expect(filterInventory(d,{...filters,transport:'in_transit'})).toHaveLength(1);});
});
