import {describe,it,expect,vi} from 'vitest';
import {seed} from '../src/lib/seed';
import {parseMobileAds,planMobileImport,buildMobileImport} from '../src/lib/mobile-import-domain';
import {applyDemoMobileImport} from '../src/lib/mobile-import';
import {fetchSellerAds} from '../src/lib/mobile-client';
const ad={mobileAdId:'801',mobileSellerId:'55',vehicleClass:'Car',vin:'WAUZZZ8V0PE444333',make:'AUDI',model:'A3',mileage:12000,exteriorColor:'BLACK',firstRegistration:'202105',constructionYear:2020,internalNumber:'EXT-90'};
function prepared(){const data=seed(),rows=parseMobileAds({ads:[ad]},'55'),plans=planMobileImport(data,rows,[],'55','production');return{data,rows,payload:buildMobileImport(plans,['0'],'55','production','Berlin','owned')};}
describe('mobile.de-Import und Serveradapter',()=>{
 it('liest nur unterstützte Felder und erfindet weder Erstzulassungstag noch Baujahr',()=>{const row=parseMobileAds({ads:[{...ad,constructionYear:undefined,description:'Private seller description',contact:{name:'Private'},firstRegistration:'202105'}]},'55')[0];expect(row).toMatchObject({make:'Audi',model:'A3',color:'Schwarz',registration_month:'202105',build_year:null});expect(row).not.toHaveProperty('description');const {payload}=prepared();expect(payload.entries[0].values).not.toHaveProperty('first_registration');expect(payload.entries[0].metadata.first_registration_month).toBe('202105');});
 it('fehlende Kilometer werden nicht als null Kilometer behauptet; falsche Monate bleiben leer',()=>{const row=parseMobileAds({ads:[{...ad,mileage:undefined,firstRegistration:'202113'}]},'55')[0];expect(row.mileage).toBeNull();expect(row.registration_month).toBe('');expect(planMobileImport(seed(),[row],[],'55','production')[0].action).toBe('blocked');});
 it('Händlerabweichungen, andere Fahrzeugklassen und mehrdeutige VINs sperren die Vorschau',()=>{const rows=parseMobileAds({ads:[ad,{...ad,mobileAdId:'802',mobileSellerId:'56',vehicleClass:'Truck'}]},'55');const plans=planMobileImport(seed(),rows,[],'55','production');expect(plans.every(plan=>plan.action==='blocked')).toBe(true);expect(plans[1].errors).toContain('Abweichende oder fehlende Händler-ID.');expect(()=>buildMobileImport(plans,['0'],'55','production','Berlin','owned')).toThrow('markierten');});
 it('VIN-Treffer werden ausdrücklich zugeordnet und ändern keine Fahrzeugdaten',()=>{const data=seed(),before=structuredClone(data.vehicles),rows=parseMobileAds({ads:[{...ad,vin:data.vehicles[0].vin,mileage:1}]},'55'),plans=planMobileImport(data,rows,[],'55','production');expect(plans[0].action).toBe('link');const next=applyDemoMobileImport(data,crypto.randomUUID(),buildMobileImport(plans,['0'],'55','production','','unassigned'),'hash','demo');expect(next.vehicles).toEqual(before);expect(next.external_listings?.[0].vehicle_id).toBe(data.vehicles[0].id);});
 it('wiederholte Abschlüsse erzeugen keine weiteren Fahrzeuge oder Zuordnungen',()=>{const {data,payload}=prepared(),id=crypto.randomUUID(),next=applyDemoMobileImport(data,id,payload,'hash','demo'),retry=applyDemoMobileImport(next,id,payload,'hash','demo');expect(retry).toBe(next);expect(next.vehicles).toHaveLength(4);expect(next.vehicles[3]).toMatchObject({plate:null,inventory_kind:'owned',inventory_status:'stock',first_registration:null});expect(()=>applyDemoMobileImport(next,id,payload,'different','demo')).toThrow('anderen Angaben');});
 it('ein später Fehler verwirft den gesamten Import; lesende Mitglieder dürfen nicht importieren',()=>{const {data,payload}=prepared(),before=structuredClone(data),invalid={...payload,entries:[payload.entries[0],{...payload.entries[0],remote_id:'802'}]};expect(()=>applyDemoMobileImport(data,crypto.randomUUID(),invalid,'hash','demo')).toThrow('VIN existiert');expect(data).toEqual(before);data.members[0].role='viewer';expect(()=>applyDemoMobileImport(data,crypto.randomUUID(),payload,'hash','demo')).toThrow('Berechtigung');});
 it('Sandbox und Produktion bleiben getrennte Inseratzuordnungen',()=>{const {data,rows,payload}=prepared(),next=applyDemoMobileImport(data,crypto.randomUUID(),payload,'hash','demo');expect(planMobileImport(next,rows,next.external_listings!,'55','production')[0].action).toBe('linked');expect(planMobileImport(next,rows,next.external_listings!,'55','sandbox')[0].action).toBe('link');});
 it('verwendet feste HTTPS-Ziele, Basic Auth, keine Weiterleitungen und ausschließlich GET',async()=>{const mock=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify({ads:[ad]})));await expect(fetchSellerAds('55','sandbox','user','secret',mock)).resolves.toEqual({ads:[ad]});const [url,init]=mock.mock.calls[0];expect(url).toBe('https://services.sandbox.mobile.de/seller-api/sellers/55/ads');expect(init).toMatchObject({redirect:'error',cache:'no-store'});expect(init?.method??'GET').toBe('GET');expect((init?.headers as Record<string,string>).Authorization).toBe('Basic '+Buffer.from('user:secret').toString('base64'));});
 it('Berechtigungsfehler und ungültige Antworten zeigen keine fremden Fehlermeldungen oder Zugangsdaten',async()=>{const denied=vi.fn<typeof fetch>().mockResolvedValue(new Response('secret provider details',{status:404}));await expect(fetchSellerAds('55','production','user','secret',denied)).rejects.toThrow('Händlerfreigabe');const broken=vi.fn<typeof fetch>().mockResolvedValue(new Response('private provider details'));await expect(fetchSellerAds('55','production','user','secret',broken)).rejects.toThrow('gültigen JSON');});
 it('zu große Antworten und manipulierte Händler-IDs werden abgewiesen',async()=>{const oversized=vi.fn<typeof fetch>().mockResolvedValue(new Response('x'.repeat(2*1024*1024+1)));await expect(fetchSellerAds('55','production','user','secret',oversized)).rejects.toThrow('größer');const mock=vi.fn<typeof fetch>();await expect(fetchSellerAds('../sellers','production','user','secret',mock)).rejects.toThrow('prüfen');expect(mock).not.toHaveBeenCalled();});
});
