// Isolated local Auth, real web UI and import RPC; no live mobile.de request.
import{execFileSync}from'node:child_process';import{createClient}from'@supabase/supabase-js';import{chromium,devices,expect}from'@playwright/test';
const s=JSON.parse(execFileSync('npx.cmd',['supabase','status','--output','json'],{encoding:'utf8',shell:true,stdio:['ignore','pipe','pipe']}));if(!new URL(s.API_URL).hostname.match(/^(127\.0\.0\.1|localhost)$/))throw Error('Local stack required');
const admin=createClient(s.API_URL,s.SERVICE_ROLE_KEY,{auth:{persistSession:false}}),browser=await chromium.launch(),users=[];let org;
const ok=result=>{if(result.error)throw Error(result.error.message);return result.data;};
async function account(){const email='import-browser-'+crypto.randomUUID()+'@example.com',password=crypto.randomUUID()+'Aa1!',user=ok(await admin.auth.admin.createUser({email,password,email_confirm:true})).user;users.push(user);const c=createClient(s.API_URL,s.PUBLISHABLE_KEY,{auth:{persistSession:false}});ok(await c.auth.signInWithPassword({email,password}));return{user,c,email,password};}
async function login(page,a){await page.goto('http://localhost:3000/');await page.getByLabel('E-Mail',{exact:true}).fill(a.email);await page.getByLabel('Passwort',{exact:true}).fill(a.password);await page.getByRole('button',{name:'Anmelden',exact:true}).click();await expect(page.getByRole('button',{name:'Organisation',exact:true})).toBeVisible();}
try{
 const owner=await account(),viewer=await account();org=ok(await owner.c.rpc('create_organization',{p_name:'Import dealer',p_member_name:'Owner'}));ok(await owner.c.rpc('add_member',{p_org:org,p_user:viewer.user.id,p_name:'Viewer',p_role:'viewer'}));const existing=crypto.randomUUID();ok(await owner.c.rpc('save_vehicle_record',{p_id:existing,p_org:org,p_revision:0,p_values:{plate:null,vin:'WVWZZZ3CZPE123456',make:'Volkswagen',model:'Golf',color:'Silver',mileage:99999,location:'Existing position',inventory_kind:'owned',inventory_status:'sold'},p_holder:null,p_holder_revision:0}));
 const mobile=await browser.newContext({...devices['Pixel 7']}),desktop=await browser.newContext(),p=await mobile.newPage(),v=await desktop.newPage(),errors=[];p.on('pageerror',error=>errors.push(error.message));v.on('pageerror',error=>errors.push(error.message));await login(p,owner);await p.getByRole('button',{name:'Organisation',exact:true}).click();await p.getByRole('tab',{name:'Anbindungen',exact:true}).click();await expect(p.getByRole('tab',{name:'Anbindungen'})).toHaveCSS('background-color','rgb(36, 93, 232)');await p.getByLabel('mobile.de-Händler-ID',{exact:true}).fill('55');
 const endpoint='http://localhost:3000/api/mobile-stock',token=(await viewer.c.auth.getSession()).data.session.access_token;expect((await p.request.post(endpoint,{data:{}})).status()).toBe(401);expect((await p.request.post(endpoint,{data:{organization_id:org,account_id:'55'},headers:{Authorization:'Bearer '+token}})).status()).toBe(403);
 await p.route('**/api/mobile-stock',route=>route.fulfill({status:503,json:{error:'Test: Anbieter nicht erreichbar'}}));await p.getByLabel('Seller-API-Benutzername',{exact:true}).fill('test-user');await p.getByLabel('Seller-API-Passwort',{exact:true}).fill('test-secret-not-persisted');await p.getByRole('button',{name:'mobile.de-Bestand laden',exact:true}).click();await expect(p.locator('.mobile-import [role="alert"]')).toContainText('Anbieter nicht erreichbar');await expect(p.getByLabel('Seller-API-Passwort',{exact:true})).toHaveValue('');await p.unroute('**/api/mobile-stock');
 const fresh={mobileAdId:'801',mobileSellerId:'55',vehicleClass:'Car',vin:'WAUZZZ8V0PE444333',make:'AUDI',model:'A3',mileage:12000,exteriorColor:'BLACK',firstRegistration:'202105',constructionYear:2020,internalNumber:'EXT-90'},file={name:'seller-ads.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({ads:[fresh,{...fresh,mobileAdId:'802',vin:'WVWZZZ3CZPE123456',mileage:1}]}))};await p.getByLabel('Seller-API-Importdatei').setInputFiles(file);await expect(p.getByRole('heading',{name:'Importvorschau'})).toBeVisible();await p.getByLabel('Position der neuen Fahrzeuge').fill('Actual dealer');await p.getByLabel('Bestandszuordnung für neue Fahrzeuge').selectOption('owned');await p.getByRole('button',{name:'Bis zu 100 Einträge auswählen'}).click();await p.screenshot({path:'docs/mobile-import-mobile.png',fullPage:true});await p.getByRole('button',{name:'Ausgewählte Fahrzeuge übernehmen'}).click();await expect(p.getByRole('status')).toContainText('Import gespeichert');
 const rows=ok(await owner.c.from('vehicles').select('*').eq('organization_id',org));expect(rows).toHaveLength(2);expect(rows.find(row=>row.id===existing)).toMatchObject({mileage:99999,location:'Existing position',inventory_status:'sold'});expect(rows.find(row=>row.id!==existing)).toMatchObject({plate:null,first_registration:null,build_year:2020,inventory_status:'stock'});expect(ok(await owner.c.from('external_listings').select('*').eq('organization_id',org))).toHaveLength(2);expect(ok(await viewer.c.from('external_listings').select('*').eq('organization_id',org))).toHaveLength(0);
 await p.getByLabel('Seller-API-Importdatei').setInputFiles(file);await expect(p.getByText('Bereits zugeordnet',{exact:true})).toHaveCount(2);await p.reload();await p.getByRole('button',{name:'Organisation',exact:true}).click();await p.getByRole('tab',{name:'Anbindungen',exact:true}).click();await expect(p.getByText(/1 neu · 1 zugeordnet/)).toBeVisible();await expect(p.getByLabel('Seller-API-Passwort',{exact:true})).toHaveValue('');await expect(p.getByLabel('Seller-API-Benutzername',{exact:true})).toHaveValue('');
 await login(v,viewer);await v.getByRole('button',{name:'Organisation',exact:true}).click();await expect(v.getByRole('tab',{name:'Anbindungen',exact:true})).toHaveCount(0);await v.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await v.getByRole('searchbox',{name:'Fahrzeuge suchen'}).fill('Audi');await expect(v.locator('tbody tr')).toHaveCount(1);expect(await p.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);expect(errors).toEqual([]);
 console.log('PASS: real local mobile import UI/RPC, explicit VIN link preserves sold vehicle, stable import history, duplicate reimport, registration month handling, private role access, provider failure retry UI, password cleared/not persisted, desktop viewer and responsive layout');
}finally{await browser.close();if(org){for(const table of['external_listings','platform_import_runs','vehicle_movements','stock_events','vehicles','memberships'])ok(await admin.from(table).delete().eq('organization_id',org));ok(await admin.from('organizations').delete().eq('id',org));}for(const user of users)ok(await admin.auth.admin.deleteUser(user.id));}
