import {describe,it,expect} from 'vitest';
import {seed} from '../src/lib/seed';
import {applyEntityUpdate,upgradeDemo} from '../src/lib/management';
import {normalizeOrderRoute,nextDriverOrders,navigationUrl,contactPhone} from '../src/lib/order-route';
import {initialProtocol,protocolErrors,updateProtocol} from '../src/lib/protocol';
function fixture(){const data=upgradeDemo(seed()),org=data.organization.id;data.sites=[{id:'pickup',organization_id:org,name:'Abholhof',address:'Straße 1, Berlin',revision:1},{id:'target',organization_id:org,name:'Zielhof',address:'Straße 2, Hamburg',revision:1}];data.spaces=[{id:'bay',organization_id:org,site_id:'target',label:'A1',revision:1}];return{data,order:data.orders[0],vehicle:data.vehicles[0]};}
describe('Standorte in Transportaufträgen',()=>{
 it('speichert Standort und Navigationsadresse unabhängig von der späteren Umbenennung',()=>{const {data,order}=fixture();const plan=normalizeOrderRoute(data,{...order,pickup_site_id:'pickup',destination_site_id:'target',destination_space_id:'bay'});expect(plan.destination).toBe('Zielhof');expect(plan.destination_address).toBe('Straße 2, Hamburg');data.sites![1].name='Neuer Name';data.sites![1].address='Neue Straße';expect(normalizeOrderRoute(data,plan,plan)).toEqual(plan);expect(navigationUrl({...plan,status:'in_transit'})).toContain(encodeURIComponent('Straße 2, Hamburg'));});
 it('begrenzt Standorte und Stellplätze auf Mandant und Zielstandort',()=>{const{data,order}=fixture();expect(()=>normalizeOrderRoute(data,{...order,destination_site_id:'other-org'})).toThrow('Unternehmen');expect(()=>normalizeOrderRoute(data,{...order,destination_site_id:'pickup',destination_space_id:'bay'})).toThrow('Zielstellplatz');});
 it('akzeptiert keinen bereits belegten neuen Zielstellplatz, bestehende Planung bleibt editierbar',()=>{const{data,order}=fixture();const plan=normalizeOrderRoute(data,{...order,destination_site_id:'target',destination_space_id:'bay'});data.vehicles[1].parking_space_id='bay';expect(()=>normalizeOrderRoute(data,plan)).toThrow('belegt');expect(normalizeOrderRoute(data,plan,plan).destination_space_id).toBe('bay');});
 it('löst veraltete Standortzuordnung bei Textänderung älterer Clients',()=>{const{data,order}=fixture();const plan=normalizeOrderRoute(data,{...order,destination_site_id:'target',destination_space_id:'bay'});const changed=normalizeOrderRoute(data,{...plan,destination:'Kundenadresse'},plan);expect(changed.destination_site_id).toBeNull();expect(changed.destination_space_id).toBeNull();expect(changed.destination_address).toBe('');expect(changed.destination).toBe('Kundenadresse');});
 it('hält die Abholung nach Übernahme fest, erlaubt Zieländerung und alte freie Aufträge',()=>{const{data,order}=fixture();data.orders[0]={...order,status:'in_transit'};expect(()=>applyEntityUpdate(data,'orders',{...data.orders[0],destination:'Kunde',destination_site_id:null},1)).not.toThrow();expect(()=>applyEntityUpdate(data,'orders',{...data.orders[0],pickup_site_id:'pickup'},1)).toThrow('Abholort');});
 it('übernimmt Ziel als Vorschlag, erfordert Bestätigung und erkennt belegte Plätze',()=>{const{data,vehicle,order}=fixture();const plan=normalizeOrderRoute(data,{...order,destination_site_id:'target',destination_space_id:'bay'}),d=initialProtocol(data,vehicle,plan,'delivery');expect(d.position.site_id).toBe('target');expect(d.position.site_revision).toBe(1);data.sites![1].revision=2;expect(protocolErrors(data,vehicle,d,false,'delivery')).toContain('Standortangaben geändert. Position erneut prüfen und bestätigen.');data.sites![1].revision=1;expect(d.position.confirmed).toBe(false);expect(Number.isNaN(d.fuel)).toBe(true);expect(protocolErrors(data,vehicle,d,false,'delivery')).toContain('Tatsächliche Position bestätigen.');data.vehicles[1].parking_space_id='bay';expect(protocolErrors(data,vehicle,d,false,'delivery')).toContain('Stellplatz belegt. Bitte eine freie Position auswählen.');d.parties.giver.signature='signature';expect(updateProtocol(d,{position:{...d.position,space_id:null}}).parties.giver.signature).toBe('');});
});
describe('Fahrerablauf',()=>{
 it('zeigt nur eigene offene Aufträge und stellt die aktuelle Fahrt vor spätere Abholungen',()=>{const{data,order}=fixture();const driver=data.drivers.find(d=>d.id===order.driver_id)!;driver.user_id='me';data.orders=[{...order,id:'later',scheduled_at:'2028-01-01T10:00:00Z'}, {...order,id:'early',scheduled_at:'2027-01-01T10:00:00Z'},{...order,id:'current',status:'in_transit',scheduled_at:'2029-01-01T10:00:00Z'},{...order,id:'closed',status:'completed'}, {...order,id:'foreign',driver_id:'not-me'}];expect(nextDriverOrders(data,'me').map(o=>o.id)).toEqual(['current','early','later']);});
 it('verwendet Kundenadressen als Navigationsziel und nur erkennbare Telefonnummern als Telefonlink',()=>{const{order}=fixture();expect(navigationUrl({...order,pickup:'Kundenstraße 2, Köln'})).toContain(encodeURIComponent('Kundenstraße 2, Köln'));expect(contactPhone('Frau Meier +49 (151) 12345678')).toBe('+4915112345678');expect(contactPhone('Herr Meier')).toBeNull();});
});
