import { describe,it,expect } from 'vitest';
import { seed } from '../src/lib/seed';
import { keySnapshot,keyValidation,validateVehicleDates } from '../src/lib/vehicle-records';
import type { Draft } from '../src/lib/domain';
describe('Fahrzeugakte und Schlüssel',()=>{
 it('unbekannt und bestätigt leer sind unterschiedliche Bestände',()=>{const data=seed(),v=data.vehicles[0],draft={mileage:0,fuel:0,signer:'',signature:'',notes:'',photos:[],damages:[],keys:{confirmed:false,revision:1,selected:[],notes:''}} as Draft;expect(keySnapshot(data,v,draft).recorded).toBe(false);expect(keyValidation(data,{...v,keys_recorded:true},draft)).toContain('Bitte Schlüsselbestand bestätigen.');draft.keys!.confirmed=true;expect(keySnapshot(data,{...v,keys_recorded:true},draft).recorded).toBe(true);expect(keyValidation(data,{...v,keys_recorded:true},draft)).toEqual([]);});
 it('fremde, doppelte und veraltete Schlüsselauswahl wird abgewiesen',()=>{const data=seed(),v={...data.vehicles[0],keys_recorded:true,keys_revision:2};data.keys=[{id:'one',vehicle_id:v.id,organization_id:v.organization_id,label:'Hauptschlüssel',identifier:'K1',location:'Schrank',state:'available',custodian:''}];const draft={mileage:0,fuel:0,signer:'',signature:'',notes:'',photos:[],damages:[],keys:{confirmed:true,revision:2,selected:['one'],notes:''}} as Draft;expect(keyValidation(data,v,draft)).toEqual([]);expect(keyValidation(data,v,{...draft,keys:{...draft.keys!,selected:['other']}})).not.toEqual([]);expect(keyValidation(data,v,{...draft,keys:{...draft.keys!,selected:['one','one']}})).not.toEqual([]);expect(keyValidation(data,v,{...draft,keys:{...draft.keys!,revision:1}})).not.toEqual([]);});
 it('Abweichung braucht Begründung und Snapshot erhält alte Schlüsselangaben',()=>{const data=seed(),v={...data.vehicles[0],keys_recorded:true};data.keys=[{id:'one',vehicle_id:v.id,organization_id:v.organization_id,label:'Alt',identifier:'K1',location:'Schrank',state:'available',custodian:''}];const draft={mileage:0,fuel:0,signer:'',signature:'',notes:'',photos:[],damages:[],keys:{confirmed:true,revision:1,selected:[],notes:''}} as Draft;expect(keyValidation(data,v,draft)).toContain('Abweichende Schlüsselanzahl benötigt eine Begründung.');draft.keys!.notes='Schlüssel bleibt im Schrank';expect(keyValidation(data,v,draft)).toEqual([]);draft.keys!.selected=['one'];const snapshot=keySnapshot(data,v,draft);data.keys[0].label='Neu';expect(snapshot.selected[0].label).toBe('Alt');});
 it('Baujahr bleibt optional und ist unabhängig von Erstzulassung',()=>{const v=seed().vehicles[0];expect(()=>validateVehicleDates({...v,build_year:null,first_registration:null})).not.toThrow();expect(()=>validateVehicleDates({...v,build_year:2020,first_registration:'2021-01-15'})).not.toThrow();expect(()=>validateVehicleDates({...v,build_year:1700})).toThrow();expect(()=>validateVehicleDates({...v,build_year:new Date().getFullYear()+2})).toThrow();expect(()=>validateVehicleDates({...v,first_registration:'2200-01-01'})).toThrow();});
});
