// Real recovery mail is captured by the isolated local Mailpit; never uses remote credentials.
import {execFileSync} from 'node:child_process';
import {createClient} from '@supabase/supabase-js';
import {chromium,devices,expect} from '@playwright/test';
import sharp from 'sharp';
const s=JSON.parse(execFileSync(process.platform==='win32'?'npx.cmd':'npx',['supabase','status','--output','json'],{encoding:'utf8',shell:process.platform==='win32',stdio:['ignore','pipe','pipe']}));
const admin=createClient(s.API_URL,s.SERVICE_ROLE_KEY,{auth:{persistSession:false}}),browser=await chromium.launch(),accounts=[],messages=[];let org;
const ok=r=>{if(r.error)throw Error(r.error.message);return r.data;};
const client=()=>createClient(s.API_URL,s.PUBLISHABLE_KEY,{auth:{persistSession:false}});
async function account(){const email='recovery-'+crypto.randomUUID()+'@example.com',password=crypto.randomUUID()+'Aa1!';const user=ok(await admin.auth.admin.createUser({email,password,email_confirm:true})).user;accounts.push(user);return{email,password,user};}
async function mailLink(email){for(let i=0;i<40;i++){const list=await(await fetch('http://127.0.0.1:55424/api/v1/messages')).json();const entry=list.messages.find(m=>m.To.some(a=>a.Address===email));if(entry){messages.push(entry.ID);const mail=await(await fetch('http://127.0.0.1:55424/api/v1/message/'+entry.ID)).json();const match=mail.HTML.match(/href="([^"]*\/auth\/v1\/verify[^"]*)"/);if(!match)throw Error('Recovery link missing from captured message');return match[1].replaceAll('&amp;','&');}await new Promise(r=>setTimeout(r,250));}throw Error('Test recovery mail was not delivered');}
try{
 const a=await account(),c=client();ok(await c.auth.signInWithPassword({email:a.email,password:a.password}));org=ok(await c.rpc('create_organization',{p_name:'Recovery '+a.user.id,p_member_name:'Owner'}));const vehicle=crypto.randomUUID();ok(await c.rpc('save_vehicle_record',{p_id:vehicle,p_org:org,p_revision:0,p_values:{plate:'REC 123',vin:'WVWZZZ3CZPE999123',make:'Volkswagen',model:'Golf',color:'Blau',mileage:100,location:'Berlin',equipment:[]},p_holder:{name:'Private Company',address:'Private Street',contact:''},p_holder_revision:0}));
 const mobile=await browser.newContext({...devices['Pixel 7']}),p=await mobile.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:3000/');await p.getByLabel('E-Mail',{exact:true}).fill(a.email);await p.getByLabel('Passwort',{exact:true}).fill(a.password);await p.getByRole('button',{name:'Anmelden',exact:true}).click();await p.getByRole('button',{name:'Fahrzeuge',exact:true}).click();await p.getByRole('button',{name:'REC 123',exact:true}).click();
 const jpeg=await sharp({create:{width:120,height:80,channels:3,background:'#6688aa'}}).jpeg().toBuffer();let failed=false;await p.route('**/storage/v1/object/vehicle-files/**',async route=>{if(route.request().method()==='POST'&&!failed){failed=true;await route.fulfill({status:503,contentType:'application/json',body:'{"error":"test interruption"}'});}else await route.continue();});
 await p.getByLabel('Fahrzeugfotos',{exact:true}).setInputFiles({name:'retry.jpg',mimeType:'image/jpeg',buffer:jpeg});await p.getByLabel('Fahrzeugschein',{exact:true}).setInputFiles({name:'registration.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n%%EOF')});await p.getByRole('button',{name:'Ausgewählte Dateien hochladen'}).click();await expect(p.getByRole('button',{name:'Erneut versuchen'})).toBeVisible();await expect(p.getByText('Gespeichert',{exact:true})).toHaveCount(1);await p.getByRole('button',{name:'Erneut versuchen'}).click();await expect(p.getByText('Gespeichert',{exact:true})).toHaveCount(2);await expect(p.locator('.asset-card')).toHaveCount(2);await p.locator('.asset-card').filter({has:p.getByText('retry.jpg',{exact:true})}).getByRole('button',{name:'Vorschau',exact:true}).click();await expect(p.locator('.asset-card img')).toBeVisible();expect(ok(await c.from('vehicle_assets').select('*').eq('vehicle_id',vehicle))).toHaveLength(2);await p.screenshot({path:'docs/vehicle-record-cloud-mobile.png',fullPage:true});await mobile.close();
 // Preserve the invitation destination through password recovery.
 const ctx=await browser.newContext(),page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:3000/');await page.getByRole('button',{name:'Passwort vergessen?'}).click();await page.getByLabel('E-Mail',{exact:true}).fill(a.email);await page.getByRole('button',{name:'Link anfordern'}).click();await expect(page.getByRole('status')).toContainText('Falls für diese Adresse');const link=await mailLink(a.email);
 await page.goto(link);await expect(page.getByLabel('Neues Passwort',{exact:true})).toBeVisible({timeout:15000});await page.getByLabel('Neues Passwort',{exact:true}).fill('NewPassword-123!');await page.getByLabel('Neues Passwort bestätigen').fill('DifferentPassword-123!');await page.getByRole('button',{name:'Passwort speichern'}).click();await expect(page.getByText('Die Passwörter stimmen nicht überein.',{exact:true})).toBeVisible();await page.reload();await expect(page.getByLabel('Neues Passwort',{exact:true})).toBeVisible();await page.getByLabel('Neues Passwort',{exact:true}).fill('NewPassword-123!');await page.getByLabel('Neues Passwort bestätigen').fill('NewPassword-123!');await page.getByRole('button',{name:'Passwort speichern'}).click();await expect(page.getByRole('status')).toContainText('wurde geändert');await page.getByRole('link',{name:'Zur Anmeldung'}).click();await expect(page.getByRole('heading',{name:'Willkommen zurück'})).toBeVisible();expect((await client().auth.signInWithPassword({email:a.email,password:a.password})).error).toBeTruthy();ok(await client().auth.signInWithPassword({email:a.email,password:'NewPassword-123!'}));
 const reused=await(await browser.newContext()).newPage();await reused.goto(link);await expect(reused.getByText('Dieser Link ist ungültig, abgelaufen oder bereits verwendet. Fordere bei der Anmeldung einen neuen Link an.')).toBeVisible();await expect(reused.getByLabel('Neues Passwort',{exact:true})).toHaveCount(0);
 const exp=await account();ok(await client().auth.resetPasswordForEmail(exp.email,{redirectTo:'http://localhost:3000/auth/reset-password'}));const expLink=await mailLink(exp.email);execFileSync('docker',['exec','supabase_db_vehicleops','psql','-U','postgres','-d','postgres','-v','ON_ERROR_STOP=1','-c',"update auth.users set recovery_sent_at=now()-interval '2 hours' where id='"+exp.user.id+"';"],{stdio:'pipe'});const expired=await(await browser.newContext()).newPage();await expired.goto(expLink);await expect(expired.getByText('Dieser Link ist ungültig, abgelaufen oder bereits verwendet. Fordere bei der Anmeldung einen neuen Link an.')).toBeVisible();await expect(expired.getByLabel('Neues Passwort',{exact:true})).toHaveCount(0);
 const regular=await(await browser.newContext()).newPage();await regular.goto('http://localhost:3000/');await regular.getByLabel('E-Mail',{exact:true}).fill(a.email);await regular.getByLabel('Passwort',{exact:true}).fill('NewPassword-123!');await regular.getByRole('button',{name:'Anmelden',exact:true}).click();await expect(regular.getByRole('heading',{name:'Alles bereit für die nächste Fahrt.'})).toBeVisible();await regular.goto('http://localhost:3000/auth/reset-password');await expect(regular.getByLabel('Neues Passwort',{exact:true})).toHaveCount(0);expect(errors).toEqual([]);
 console.log('PASS: mobile private uploads, failure/progress/retry, captured recovery mail, valid/reloaded recovery session, password confirmation, changed password login, reused/expired links and ordinary-session rejection');
}finally{
 await browser.close();if(org){const assets=ok(await admin.from('vehicle_assets').select('path').eq('organization_id',org));if(assets.length)ok(await admin.storage.from('vehicle-files').remove(assets.map(a=>a.path)));for(const table of ['vehicle_movements','vehicle_assets','vehicle_holders','vehicle_events','vehicles','memberships'])ok(await admin.from(table).delete().eq('organization_id',org));ok(await admin.from('organizations').delete().eq('id',org));}for(const a of accounts)ok(await admin.auth.admin.deleteUser(a.id));if(messages.length)await fetch('http://127.0.0.1:55424/api/v1/messages',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({IDs:messages})});
}

