'use client';
import {useEffect,useState} from 'react';
import Image from 'next/image';
import {Data,Organization} from '@/lib/domain';
import {businessLabels,companyLogo,normalizedImage,profileFields,saveCompany} from '@/lib/company';
import {Team} from './team';
export function Company({data,cloud,userId,onChange}:{data:Data;cloud:boolean;userId:string;onChange:(data:Data|null)=>void}){
 const admin=data.members.some(m=>m.user_id===userId&&m.role==='admin'),[tab,setTab]=useState('company'),[editing,setEditing]=useState<Organization|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[logo,setLogo]=useState(''),[remove,setRemove]=useState(false),[preview,setPreview]=useState('');
 useEffect(()=>{let live=true;companyLogo(data.organization,cloud).then(url=>{if(live)setLogo(url);}).catch(()=>{if(live)setLogo('');});const timer=setInterval(()=>{void companyLogo(data.organization,cloud).then(url=>{if(live)setLogo(url);}).catch(()=>{});},240000);return()=>{live=false;clearInterval(timer);};},[data.organization,cloud]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{const file=f.get('logo');onChange(await saveCompany(data,{...editing!,name:String(f.get('name')),business_type:f.get('business_type') as Organization['business_type'],profile:Object.fromEntries(profileFields.map(([key])=>[key,String(f.get(key)??'').trim()]))},file instanceof File&&file.size?file:null,remove,cloud));setEditing(null);}catch(err){setError(err instanceof Error?err.message:'Speichern fehlgeschlagen.');}finally{setBusy(false);}}
 return <><div className="section-tabs" role="tablist" aria-label="Organisation"><button role="tab" aria-selected={tab==='company'} onClick={()=>setTab('company')}>Unternehmen</button><button role="tab" aria-selected={tab==='team'} onClick={()=>setTab('team')}>Team</button></div>{tab==='team'?<Team data={data} cloud={cloud} userId={userId} onChange={onChange}/>:<section className="panel company-panel">{error&&<p className="alert" role="alert">{error}</p>}<div className="company-header">{logo&&<Image src={logo} width={180} height={90} unoptimized className="company-logo" alt={'Logo '+data.organization.name}/>}<div><h2>{data.organization.name}</h2><p className="muted">{businessLabels[data.organization.business_type??'combined']}</p></div>{admin&&!editing&&<button className="secondary" onClick={()=>{setEditing({...data.organization});setRemove(false);setPreview('');setError('');}}>Unternehmen bearbeiten</button>}</div>{editing?<form onSubmit={save}><fieldset disabled={busy} className="form-grid"><label>Firmenname<input name="name" required maxLength={120} defaultValue={editing.name}/></label><label>Unternehmensart<select aria-label="Unternehmensart" name="business_type" defaultValue={editing.business_type??'combined'}>{Object.entries(businessLabels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label>{profileFields.map(([key,label])=><label key={key}>{label}<input name={key} type={key==='email'?'email':key==='website'?'url':'text'} maxLength={300} defaultValue={editing.profile?.[key]??''}/></label>)}<label className="span-2">Unternehmenslogo<input type="file" name="logo" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];setPreview('');if(file)try{setPreview(await normalizedImage(file));setError('');}catch(err){setError(err instanceof Error?err.message:'Logo konnte nicht gelesen werden.');e.target.value='';}}}/>{preview&&<Image src={preview} alt="Vorschau des neuen Unternehmenslogos" width={180} height={90} unoptimized className="company-logo"/>}<small className="muted">JPEG, PNG oder WebP · bis 10 MB</small></label>{logo&&<label className="span-2 checkbox-label"><input type="checkbox" checked={remove} onChange={e=>setRemove(e.target.checked)}/>Aktuelles Logo entfernen</label>}<div className="record-actions span-2"><button className="primary">{busy?'Wird gespeichert …':'Unternehmen speichern'}</button><button type="button" className="secondary" onClick={()=>setEditing(null)}>Abbrechen</button></div></fieldset></form>:<dl className="company-details">{profileFields.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{data.organization.profile?.[key]||'Nicht angegeben'}</dd></div>)}</dl>}</section>}</>;
}
