'use client';
import { useEffect, useState } from 'react';
import { PhotoWalkaround } from './photo-walkaround';
import { ChevronLeft, Plus, Trash2, ShieldCheck } from 'lucide-react';
import { Data, Draft, Kind, Order, requiredPhotoCount, validateHandover } from '@/lib/domain';
import { clearDraft, finalize, readDraft, saveDraft } from '@/lib/repository';
import { Signature } from './signature';
import { KeyChecklistFields } from './key-checklist';
import { keyValidation } from '@/lib/vehicle-records';
async function compress(file: File) {
 if (!file.type.startsWith('image/')) throw new Error('Bitte eine Bilddatei auswählen.');
 const image = await createImageBitmap(file); const ratio = Math.min(1, 1280 / Math.max(image.width, image.height));
 const canvas = document.createElement('canvas'); canvas.width = Math.round(image.width * ratio); canvas.height = Math.round(image.height * ratio);
 canvas.getContext('2d')!.drawImage(image, 0, 0, canvas.width, canvas.height); image.close(); return canvas.toDataURL('image/jpeg', .8);
}
export function Inspection({ data, order, kind, cloud, userId, onDone, onBack }: { data: Data; order: Order; kind: Kind; cloud: boolean; userId: string; onDone: (data: Data) => void; onBack: () => void }) {
 const vehicle = data.vehicles.find(v => v.id === order.vehicle_id)!;
 const key = `${cloud ? userId : 'demo'}:${data.organization.id}:${order.id}:${kind}${(order.revision ?? 1) > 1 ? `:${order.revision}` : ''}`;
 const [draft, setDraft] = useState<Draft>({ mileage: vehicle.mileage, fuel: 75, signer: '', signature: '', notes: '', photos: [], damages: [],keys:{confirmed:false,selected:[],notes:'',revision:vehicle.keys_revision??1} });
 const [ready, setReady] = useState(false), [error, setError] = useState(''), [busy, setBusy] = useState(false), [saved, setSaved] = useState(false);
 const [photosProcessing, setPhotosProcessing] = useState(0);
 useEffect(() => { let active = true; readDraft(key).then(value => { if (active) { if (value) setDraft(value); setReady(true); } }).catch(() => { if (active) { setError('Entwurf konnte nicht geladen werden.'); setReady(true); } }); return () => { active = false; }; }, [key]);
 useEffect(() => { if (!ready) return; const timer = setTimeout(() => { saveDraft(key, draft).then(() => setSaved(true)).catch(() => { setSaved(false); setError('Entwurf konnte nicht gespeichert werden. Speicherplatz prüfen.'); }); }, 500); return () => clearTimeout(timer); }, [draft, key, ready]);
 function update(patch: Partial<Draft>) { setSaved(false); setDraft(d => ({ ...d, ...patch })); }
 const missing = [...validateHandover(draft, order, vehicle, data.handovers, kind),...keyValidation(data,vehicle,draft)];
 async function finish() { setError(''); setBusy(true); try { const next = await finalize(data, order, kind, draft, cloud); await clearDraft(key); if (next) onDone(next); } catch (e) { setError(e instanceof Error ? e.message : 'Abschluss fehlgeschlagen.'); } finally { setBusy(false); } }
 return <div className="inspection"><button className="text-button back" disabled={busy || photosProcessing > 0} onClick={onBack}><ChevronLeft size={17} /> Zurück zum Auftrag</button><div className="page-heading"><div><p className="eyebrow">{order.reference} / {vehicle.plate}</p><h1>{kind === 'pickup' ? 'Fahrzeug übernehmen' : 'Fahrzeug übergeben'}</h1><p className="muted">{vehicle.make} {vehicle.model} · {kind === 'pickup' ? order.pickup : order.destination}</p></div><span className="badge">{saved ? 'Entwurf lokal gespeichert' : 'Entwurf'}</span></div>
 {error && <div role="alert" className="alert">{error}</div>}
 <fieldset disabled={busy || photosProcessing > 0} className="inspection-fields"><div className="inspection-layout"><div><section className="panel"><h2>1. Fahrzeugzustand</h2><div className="form-grid"><label>Kilometerstand<input type="number" min={vehicle.mileage} value={Number.isNaN(draft.mileage) ? '' : draft.mileage} onChange={e => update({ mileage: e.target.value === '' ? NaN : Number(e.target.value) })} /></label><label>Tank-/Ladestand (%)<input type="number" min="0" max="100" value={Number.isNaN(draft.fuel) ? '' : draft.fuel} onChange={e => update({ fuel: e.target.value === '' ? NaN : Number(e.target.value) })} /></label></div></section>
 <section className="panel"><div className="section-heading"><div><h2>2. Fotodokumentation</h2><p className="muted">Alle zehn Perspektiven sind verpflichtend. Innenraumfotos können ergänzt werden.</p></div><span className="badge">{requiredPhotoCount(draft.photos)} / 10</span></div><PhotoWalkaround photos={draft.photos} disabled={busy || !ready || photosProcessing > 0} onPhotos={async (shot, files) => { setPhotosProcessing(count => count + 1); try { const photos = await Promise.all(files.map(async file => ({ slot: shot, url: await compress(file) }))); setDraft(d => ({ ...d, photos: shot === 'Innenraum' ? [...d.photos, ...photos] : [...d.photos.filter(p => p.slot !== shot), ...photos.slice(0, 1)] })); setSaved(false); } catch (e) { setError(e instanceof Error ? e.message : 'Bilder konnten nicht gelesen werden.'); } finally { setPhotosProcessing(count => count - 1); } }} onRemovePhoto={index => update({ photos: draft.photos.filter((_, i) => i !== index) })} /></section>
 <section className="panel"><h2>3. Schäden dokumentieren</h2>{data.damages.filter(d => d.vehicle_id === vehicle.id).length > 0 && <div className="known-damages"><strong>Bereits dokumentiert</strong>{data.damages.filter(d => d.vehicle_id === vehicle.id).map(d => <p key={d.id}>{d.area}: {d.description}</p>)}</div>}{draft.damages.map((damage, i) => <div className="damage-row" key={i}><label>Bereich<input value={damage.area} placeholder="z. B. Felge vorne rechts" onChange={e => update({ damages: draft.damages.map((d, index) => index === i ? { ...d, area: e.target.value } : d) })} /></label><label>Beschreibung<input value={damage.description} placeholder="Art und Umfang des Schadens" onChange={e => update({ damages: draft.damages.map((d, index) => index === i ? { ...d, description: e.target.value } : d) })} /></label><button aria-label="Schaden entfernen" className="icon-button" onClick={() => update({ damages: draft.damages.filter((_, index) => i !== index) })}><Trash2 size={18} /></button></div>)}<button className="secondary" onClick={() => update({ damages: [...draft.damages, { area: '', description: '' }] })}><Plus size={16} /> Schaden hinzufügen</button><label className="mt">Anmerkungen<textarea value={draft.notes} onChange={e => update({ notes: e.target.value })} placeholder="Zubehör, Schlüssel oder weitere Hinweise" /></label></section>
 <KeyChecklistFields data={data} vehicle={vehicle} draft={draft} onChange={update}/><section className="panel"><h2>4. Bestätigung und Unterschrift</h2><label>Name der unterzeichnenden Person<input value={draft.signer} onChange={e => update({ signer: e.target.value })} placeholder="Vor- und Nachname" /></label><p className="muted mt">Mit der Unterschrift wird der oben dokumentierte Fahrzeugzustand bestätigt.</p><Signature value={draft.signature} onChange={signature => update({ signature })} /></section></div>
 <aside className="completion panel"><ShieldCheck size={26} /><h2>Bereit zum Abschluss?</h2><p className="muted">Das abgeschlossene Protokoll kann anschließend als PDF heruntergeladen werden.</p><ul className="checklist"><li><span className={requiredPhotoCount(draft.photos) === 10 ? 'ok' : ''}>{requiredPhotoCount(draft.photos) === 10 ? '✓' : '○'}</span> Zehn Pflichtperspektiven</li><li><span className={draft.signer.trim() ? 'ok' : ''}>{draft.signer.trim() ? '✓' : '○'}</span> Name erfasst</li><li><span className={draft.signature ? 'ok' : ''}>{draft.signature ? '✓' : '○'}</span> Unterschrift erfasst</li></ul>{missing.length > 0 && <p className="muted small">{missing[0]}</p>}<button className="primary full" disabled={busy || !ready || photosProcessing > 0 || missing.length > 0} onClick={finish}>{busy ? 'Wird abgeschlossen …' : 'Protokoll abschließen'}</button><p className="muted small mt">Der Abschluss ist verbindlich gespeichert. Entwürfe bleiben auf diesem Gerät.</p></aside></div></fieldset></div>;
}




