'use client';
import { useEffect, useState } from 'react';
import { PhotoWalkaround } from './photo-walkaround';
import { ChevronLeft, Plus, Trash2, ShieldCheck } from 'lucide-react';
import { Data, ProtocolDraft, Vehicle, Kind, Order, requiredPhotoCount } from '@/lib/domain';
import { clearDraft, readDraft, saveDraft } from '@/lib/repository';
import {ProtocolParticipants,ProtocolConfirmation} from './protocol-details';
import {initialProtocol,finalizeProtocol,protocolErrors,updateProtocol} from '@/lib/protocol';
import {vehicleTitle,vehicleIdentity} from '@/lib/company';
import {CompanyMark} from './company-mark';
import { KeyChecklistFields } from './key-checklist';

async function compress(file: File) {
 if (!file.type.startsWith('image/')||file.size>10*1024*1024) throw new Error('Bitte eine Bilddatei auswählen.');
 const image = await createImageBitmap(file); const ratio = Math.min(1, 1280 / Math.max(image.width, image.height));
 const canvas = document.createElement('canvas'); canvas.width = Math.round(image.width * ratio); canvas.height = Math.round(image.height * ratio);
 canvas.getContext('2d')!.drawImage(image, 0, 0, canvas.width, canvas.height); image.close(); return canvas.toDataURL('image/jpeg', .8);
}
export function Inspection({ data, order, vehicle:provided, kind, cloud, userId, onDone, onBack }: { data: Data; order: Order|null;vehicle?:Vehicle; kind: Kind; cloud: boolean; userId: string; onDone: (data: Data) => void; onBack: () => void }) {
 const vehicle = provided??data.vehicles.find(v => v.id === order!.vehicle_id)!;
 const key = `${cloud ? userId : 'demo'}:${data.organization.id}:v2:${order?.id??vehicle.id}:${kind}:${order?.revision??vehicle.revision??1}`;
 const [draft,setDraft]=useState<ProtocolDraft>(()=>{const d=initialProtocol(data,vehicle,order,kind);const member=data.members.find(m=>m.user_id===userId),self=kind==='pickup'?'receiver':'giver',counterpart=kind==='pickup'?'giver':'receiver';d.parties[self].name=member?.name??'';d.parties[self].role=member?.role==='driver'?'Fahrer':'Mitarbeiter';d.parties[counterpart].role='Ansprechpartner';return d;});
 const [ready, setReady] = useState(false), [error, setError] = useState(''), [busy, setBusy] = useState(false), [saved, setSaved] = useState(false);
 const [photosProcessing, setPhotosProcessing] = useState(0);
 useEffect(() => { let active = true; readDraft(key).then(value => { if (active) { if (value&&'parties' in value) setDraft(value as ProtocolDraft); setReady(true); } }).catch(() => { if (active) { setError('Entwurf konnte nicht geladen werden.'); setReady(true); } }); return () => { active = false; }; }, [key]);
 useEffect(() => { if (!ready) return; const timer = setTimeout(() => { saveDraft(key, draft).then(() => setSaved(true)).catch(() => { setSaved(false); setError('Entwurf konnte nicht gespeichert werden. Speicherplatz prüfen.'); }); }, 500); return () => clearTimeout(timer); }, [draft, key, ready]);
 function update(patch:Partial<ProtocolDraft>,signing=false){setSaved(false);setDraft(d=>updateProtocol(d,patch,signing));}
 const missing = protocolErrors(data,vehicle,draft,!order);
 const complete=[!!(draft.parties.giver.name.trim()&&draft.parties.giver.role.trim()&&draft.parties.receiver.name.trim()&&draft.parties.receiver.role.trim()&&(order||draft.position.confirmed&&(vehicle.inventory_kind!=='owned'||draft.stock_confirmed))),Number.isSafeInteger(draft.mileage)&&draft.mileage>=vehicle.mileage&&draft.fuel>=0&&draft.fuel<=100&&!missing.some(m=>/Schlüssel|Schaden/.test(m)),requiredPhotoCount(draft.photos)===10,missing.length===0];
 async function finish() { setError(''); setBusy(true); try { const next = await finalizeProtocol(data,vehicle,order,kind,draft,cloud); await clearDraft(key); if (next) onDone(next); } catch (e) { setError(e instanceof Error ? e.message : 'Abschluss fehlgeschlagen.'); } finally { setBusy(false); } }
 return <div className="inspection"><button className="text-button back" disabled={busy || photosProcessing > 0} onClick={onBack}><ChevronLeft size={17} /> {order?'Zurück zum Auftrag':'Zurück zum Fahrzeug'}</button><div className="page-heading"><div><div className="protocol-company"><CompanyMark organization={data.organization} cloud={cloud}/><strong>{data.organization.name}</strong></div><p className="eyebrow">{order?.reference??vehicleIdentity(vehicle)} / {vehicleTitle(vehicle)}</p><h1>{kind === 'pickup' ? 'Fahrzeug übernehmen' : 'Fahrzeug übergeben'}</h1><p className="muted">{vehicle.make} {vehicle.model} · {order?(kind === 'pickup' ? order.pickup : order.destination):vehicle.location}</p></div><span className="badge">{saved ? 'Entwurf lokal gespeichert' : 'Entwurf'}</span></div>
 <nav className="protocol-steps" aria-label="Protokollabschnitte">{['Vorgang','Zustand','Fotos','Prüfen & unterschreiben'].map((label,i)=><button key={label} disabled={busy||photosProcessing>0} onClick={()=>document.getElementById('protocol-step-'+i)?.scrollIntoView({behavior:'smooth',block:'start'})}><span>{complete[i]?'✓':i+1}</span>{label}</button>)}</nav>
 {draft.company_revision!==(data.organization.revision??1)&&<div className="notice"><p>Das Unternehmensprofil hat sich geändert. Bitte das neue Profil und alle Angaben vor dem Unterschreiben prüfen.</p><button className="secondary" onClick={()=>update({company_revision:data.organization.revision??1})}>Aktuelles Unternehmensprofil übernehmen</button></div>}{error && <div role="alert" className="alert">{error}</div>}
 <fieldset disabled={busy || photosProcessing > 0} className="inspection-fields"><div className="inspection-layout"><div><ProtocolParticipants data={data} vehicle={vehicle} order={order} kind={kind} draft={draft} onChange={update}/><section className="panel" id="protocol-step-1"><h2>2. Fahrzeugzustand</h2><div className="form-grid"><label>Kilometerstand<input type="number" min={vehicle.mileage} value={Number.isNaN(draft.mileage) ? '' : draft.mileage} onChange={e => update({ mileage: e.target.value === '' ? NaN : Number(e.target.value) })} /></label><label>Tank-/Ladestand (%)<input type="number" min="0" max="100" value={Number.isNaN(draft.fuel) ? '' : draft.fuel} onChange={e => update({ fuel: e.target.value === '' ? NaN : Number(e.target.value) })} /></label></div></section>
 <section className="panel"><h2>Schäden dokumentieren</h2>{data.damages.filter(d => d.vehicle_id === vehicle.id).length > 0 && <div className="known-damages"><strong>Bereits dokumentiert</strong>{data.damages.filter(d => d.vehicle_id === vehicle.id).map(d => <p key={d.id}>{d.area}: {d.description}</p>)}</div>}{draft.damages.map((damage, i) => <div className="damage-row" key={i}><label>Bereich<input value={damage.area} placeholder="z. B. Felge vorne rechts" onChange={e => update({ damages: draft.damages.map((d, index) => index === i ? { ...d, area: e.target.value } : d) })} /></label><label>Beschreibung<input value={damage.description} placeholder="Art und Umfang des Schadens" onChange={e => update({ damages: draft.damages.map((d, index) => index === i ? { ...d, description: e.target.value } : d) })} /></label><button aria-label="Schaden entfernen" className="icon-button" onClick={() => update({ damages: draft.damages.filter((_, index) => i !== index) })}><Trash2 size={18} /></button></div>)}<button className="secondary" onClick={() => update({ damages: [...draft.damages, { area: '', description: '' }] })}><Plus size={16} /> Schaden hinzufügen</button><label className="mt">Anmerkungen<textarea value={draft.notes} onChange={e => update({ notes: e.target.value })} placeholder="Zubehör, Schlüssel oder weitere Hinweise" /></label></section>
 <KeyChecklistFields data={data} vehicle={vehicle} draft={draft} onChange={update}/>
 <section className="panel" id="protocol-step-2"><div className="section-heading"><div><h2>3. Fotodokumentation</h2><p className="muted">Alle zehn Perspektiven sind verpflichtend. Innenraumfotos können ergänzt werden.</p></div><span className="badge">{requiredPhotoCount(draft.photos)} / 10</span></div><PhotoWalkaround photos={draft.photos} disabled={busy || !ready || photosProcessing > 0} onPhotos={async (shot, files) => { setPhotosProcessing(count => count + 1); try { const photos = await Promise.all(files.map(async file => ({ slot: shot, url: await compress(file) }))); setDraft(d => updateProtocol(d,{photos:shot==='Innenraum'?[...d.photos,...photos]:[...d.photos.filter(p=>p.slot!==shot),...photos.slice(0,1)]})); setSaved(false); } catch (e) { setError(e instanceof Error ? e.message : 'Bilder konnten nicht gelesen werden.'); } finally { setPhotosProcessing(count => count - 1); } }} onRemovePhoto={index => update({ photos: draft.photos.filter((_, i) => i !== index) })} /></section>
 <ProtocolConfirmation data={data} vehicle={vehicle} order={order} kind={kind} draft={draft} onChange={update}/></div>
 <aside className="completion panel"><ShieldCheck size={26} /><h2>Bereit zum Abschluss?</h2><p className="muted">Das abgeschlossene Protokoll kann anschließend als PDF heruntergeladen werden.</p><ul className="checklist"><li><span className={requiredPhotoCount(draft.photos) === 10 ? 'ok' : ''}>{requiredPhotoCount(draft.photos) === 10 ? '✓' : '○'}</span> Zehn Pflichtperspektiven</li><li><span className={draft.parties.giver.name&&draft.parties.receiver.name?'ok':''}>{draft.parties.giver.name&&draft.parties.receiver.name?'✓':'○'}</span> Beide Beteiligten erfasst</li><li><span className={draft.parties.giver.signature&&draft.parties.receiver.signature?'ok':''}>{draft.parties.giver.signature&&draft.parties.receiver.signature?'✓':'○'}</span> Unterschriften / Ausnahme</li></ul>{missing.length>0&&<ul className="muted small">{missing.map(message=><li key={message}>{message}</li>)}</ul>}<button className="primary full" disabled={busy || !ready || photosProcessing > 0 || missing.length > 0} onClick={finish}>{busy ? 'Wird abgeschlossen …' : 'Protokoll abschließen'}</button><p className="muted small mt">Der Abschluss ist verbindlich gespeichert. Entwürfe bleiben auf diesem Gerät.</p></aside></div></fieldset></div>;
}




