'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import {X,FileDown} from 'lucide-react';
import {Data,Handover} from '@/lib/domain';
import {resolveProtocol} from '@/lib/vehicle-images';
import {vehicleTitle,stockLabels} from '@/lib/company';
import {purposeLabels} from '@/lib/protocol';
import {CompanyMark} from './company-mark';
export function ProtocolViewer({data,handover,cloud,onClose,onDownload}:{data:Data;handover:Handover;cloud:boolean;onClose:()=>void;onDownload:()=>void}){
 const [resolved,setResolved]=useState<Handover|null>(null),[error,setError]=useState(''),ref=useRef<HTMLElement>(null);
 useEffect(()=>{let active=true;const refresh=()=>{void resolveProtocol(handover,cloud).then(h=>{if(active)setResolved(h);}).catch(()=>{if(active)setError('Bilder konnten nicht geladen werden. Bitte die Ansicht erneut öffnen.');});};refresh();const timer=setInterval(refresh,240000);return()=>{active=false;clearInterval(timer);};},[handover,cloud]);
 useEffect(()=>{const old=document.activeElement as HTMLElement|null,modal=ref.current!;modal.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key!=='Tab')return;const all=Array.from(modal.querySelectorAll<HTMLElement>('button:not(:disabled),a[href]'));if(e.shiftKey&&document.activeElement===all[0]){e.preventDefault();all.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===all.at(-1)){e.preventDefault();all[0]?.focus();}};modal.addEventListener('keydown',key);return()=>{modal.removeEventListener('keydown',key);old?.focus();};},[onClose]);
 const h=resolved??handover,s=h.snapshot,v=s?.vehicle,org=s?.organization,damages=data.damages.filter(d=>d.handover_id===h.id);
 return <div className="modal-backdrop" onClick={onClose}><section ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="protocol-view-title" className="modal protocol-viewer" onClick={e=>e.stopPropagation()}>
 <div className="section-heading"><div>{org&&<CompanyMark organization={org} cloud={cloud}/>}<p className="eyebrow">{s?.organization_name??'Unternehmen'}</p>{org&&<p className="muted small">{[org.profile?.street,org.profile?.postal_code,org.profile?.city,org.profile?.email,org.profile?.phone,org.profile?.website].filter(Boolean).join(' · ')}</p>}<h2 id="protocol-view-title">{h.kind==='pickup'?'Fahrzeugübernahme':'Fahrzeugübergabe'}</h2><p className="muted small">{new Date(h.created_at).toLocaleString('de-DE')} · {s?.order?.reference??h.id.slice(0,8).toUpperCase()}</p></div><div className="detail-actions"><button className="secondary" onClick={onDownload}><FileDown size={16}/>PDF</button><button className="icon-button" aria-label="Protokoll schließen" onClick={onClose}><X size={20}/></button></div></div>
 {error&&<p className="alert" role="alert">{error}</p>}{h.version!==2&&<p className="notice">Ältere Protokollversion · eine Unterschrift</p>}
 <section className="protocol-section"><h3>Fahrzeug und Vorgang</h3><dl><dt>Fahrzeug</dt><dd>{v?vehicleTitle(v):'Historische Fahrzeugakte'}</dd><dt>Bestandsnummer / VIN</dt><dd>{v?.stock_number??'Nicht erfasst'} · {v?.vin}</dd><dt>Zulassungskennzeichen</dt><dd>{v?.plate??'Nicht zugeordnet'}</dd><dt>Transportkennzeichen</dt><dd>{h.transport_plate||'Nicht angegeben'}</dd><dt>Anlass</dt><dd>{purposeLabels[h.purpose??'transport']}</dd>{s?.order&&<><dt>Route</dt><dd>{s.order.pickup} → {s.order.destination}</dd></>}<dt>Bestätigte Position</dt><dd>{h.position?.location??(h.kind==='pickup'?s?.order?.pickup:s?.order?.destination)}{h.position?.space_label?' · '+h.position.space_label:''}</dd>{v?.inventory_kind==='owned'&&<><dt>Bestandsstatus</dt><dd>{v.inventory_status?stockLabels[v.inventory_status]:'Nicht erfasst'} → {h.position?.stock_status?stockLabels[h.position.stock_status]:'Nicht erfasst'}</dd></>}</dl></section>
 <section className="protocol-section"><h3>Zustand, Schäden und Schlüssel</h3><p>{h.mileage.toLocaleString('de-DE')} km · Tank/Ladung {h.fuel} %</p>{s?.known_damages?.map(d=><p key={d.id}><strong>Bekannt · {d.area}</strong>: {d.description}</p>)}{damages.map(d=><p key={d.id}><strong>{d.area}</strong>: {d.description}</p>)}{!damages.length&&<p className="muted">Keine neuen Schäden dokumentiert.</p>}<p>{h.key_snapshot?.recorded?`${h.key_snapshot.selected.length} von ${h.key_snapshot.expected_count} erfassten Schlüsseln bestätigt`:'Schlüsselbestand nicht erfasst'}</p>{h.key_snapshot?.selected.map(k=><p key={k.id}>{k.label}{k.identifier?' · '+k.identifier:''}</p>)}{h.key_snapshot?.notes&&<p>Schlüsselabweichung: {h.key_snapshot.notes}</p>}<p>Hinweise: {h.notes||'Keine'}</p></section>
 <section className="protocol-section"><h3>Bestätigung und Unterschriften</h3>{h.parties?<><div className="dual-signatures">{[h.parties.giver,h.parties.receiver].map((p,i)=><div key={i}><h4>{i?'Übernehmende':'Übergebende'} Person</h4><p>{p.name} · {p.role}</p>{(p.signature_url??(!cloud?p.signature:''))?<Image src={p.signature_url??p.signature} alt={'Unterschrift '+p.name} width={400} height={150} unoptimized/>:<p className="muted">{p.signature?'Bild wird geladen …':'Unterschrift fehlt · begründete Ausnahme'}</p>}</div>)}</div>{h.parties.exception_confirmed&&<p>Ausnahme: {h.parties.exception_reason}</p>}</>:<><p>{h.signer}</p>{resolved&&<Image src={h.signature} alt={'Unterschrift '+h.signer} width={400} height={150} unoptimized/>}</>}</section>
 <section className="protocol-section"><h3>Fotodokumentation</h3><div className="protocol-photo-grid">{h.photos.map((p,i)=><figure key={p.id??i}>{p.url&&<Image src={p.url} alt={p.slot} width={640} height={480} unoptimized loading="lazy"/>}<figcaption>{p.slot}</figcaption></figure>)}</div></section>{org&&<p className="protocol-legal muted small">{[org.profile?.legal_form,org.profile?.management,org.profile?.tax_number,org.profile?.vat_id,org.profile?.register_court,org.profile?.register_number].filter(Boolean).join(' · ')}</p>}<p className="muted small">Protokoll-ID: {h.id}</p>
 </section></div>;
}
