'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { recoveryState, supabase } from '@/lib/supabase';
export function ResetPassword() {
 const [returnPath,setReturnPath]=useState('/');
 const [ready,setReady]=useState(false),[allowed,setAllowed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 useEffect(()=>{let active=true;async function check(){const invite=new URLSearchParams(window.location.search).get('invite');if(invite)setReturnPath('/?invite='+encodeURIComponent(invite));if(!supabase){if(active){setError('Passwort-Wiederherstellung benötigt den Cloud-Modus.');setReady(true);}return;}const auth=await supabase.auth.getUser();let marker:{user?:string;until?:number}={};try{marker=JSON.parse(sessionStorage.getItem('vehicleops-recovery')??'{}');}catch{}if(active){setAllowed(!auth.error&&!!auth.data.user&&(recoveryState.active||(marker.user===auth.data.user.id&&(marker.until??0)>Date.now())));setReady(true);}}void check();return()=>{active=false;};},[]);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const values=new FormData(event.currentTarget),password=String(values.get('password'));if(password!==values.get('repeat')){setError('Die Passwörter stimmen nicht überein.');return;}setBusy(true);setError('');try{const auth=await supabase!.auth.getUser();if(auth.error||!auth.data.user||!allowed)throw new Error('Der Link ist ungültig oder abgelaufen.');const result=await supabase!.auth.updateUser({password});if(result.error)throw new Error(result.error.message);recoveryState.active=false;sessionStorage.removeItem('vehicleops-recovery');await supabase!.auth.signOut();setDone(true);}catch(e){setError(e instanceof Error?e.message:'Passwort konnte nicht geändert werden.');}finally{setBusy(false);}}
 return <main className="reset-page"><section className="panel"><p className="eyebrow">VehicleOps</p><h1>Passwort zurücksetzen</h1>{error&&<p role="alert" className="alert">{error}</p>}{!ready?<p>Link wird geprüft …</p>:done?<><p role="status">Dein Passwort wurde geändert. Melde dich mit dem neuen Passwort an.</p><Link className="primary" href={returnPath}>Zur Anmeldung</Link></>:!allowed?<><p>Dieser Link ist ungültig, abgelaufen oder bereits verwendet. Fordere bei der Anmeldung einen neuen Link an.</p><Link className="text-button" href={returnPath}>Zur Anmeldung</Link></>:<form onSubmit={submit}><fieldset disabled={busy} className="record-fields"><label>Neues Passwort<input name="password" type="password" required minLength={8} autoComplete="new-password"/></label><label>Neues Passwort bestätigen<input name="repeat" type="password" required minLength={8} autoComplete="new-password"/></label><button className="primary">{busy?'Wird gespeichert …':'Passwort speichern'}</button></fieldset></form>}</section></main>;
}
