'use client';
import { useEffect, useState } from 'react';
import { Data, Member, Role } from '@/lib/domain';
import { changeMember, createInvitation, revokeInvitation, roleLabels } from '@/lib/team';
export function Team({ data, cloud, userId, onChange }: { data: Data; cloud: boolean; userId: string; onChange: (data: Data | null) => void }) {
 const admin = data.members.some(m => m.user_id === userId && m.role === 'admin');
 const [now, setNow] = useState(() => Date.now());
 useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 60000); return () => clearInterval(timer); }, []);
 const [busy, setBusy] = useState(false), [error, setError] = useState(''), [link, setLink] = useState(''), [copied, setCopied] = useState(false);
 const [confirm, setConfirm] = useState<{ member: Member; role: Role; remove: boolean } | null>(null);
 async function run(fn: () => Promise<Data | null>) { setBusy(true); setError(''); try { onChange(await fn()); setConfirm(null); } catch (e) { setError(e instanceof Error ? e.message : 'Änderung fehlgeschlagen.'); } finally { setBusy(false); } }
 async function invite(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget, values = new FormData(form); setBusy(true); setError(''); try { const result = await createInvitation(data, String(values.get('email')), String(values.get('name')), values.get('role') as Role, cloud); onChange(result.data); setLink(window.location.origin + '/?invite=' + result.token); setCopied(false); form.reset(); } catch (e) { setError(e instanceof Error ? e.message : 'Einladung fehlgeschlagen.'); } finally { setBusy(false); } }
 const pending = data.invitations.filter(i => !i.accepted_at && !i.revoked_at && new Date(i.expires_at).getTime() > now);
 return <div className="team-layout">{error && <div className="alert" role="alert">{error}</div>}
 <section className="panel"><h2>{data.organization.name}</h2><p className="muted">{cloud ? 'Gemeinsamer Arbeitsbereich für dein Team.' : 'Lokale Demo: Einladungen und Rollen lassen sich ausprobieren. Andere Geräte benötigen die Cloud-Anbindung.'}</p><h2 className="mt">Teammitglieder</h2>
 {data.members.map(m => <div className="team-member" key={m.id}><div><strong>{m.name}{m.user_id === userId ? ' (du)' : ''}</strong><p className="muted small">{roleLabels[m.role]}</p></div>{admin && <div className="team-actions"><select aria-label={`Rolle für ${m.name}`} value={m.role} disabled={busy} onChange={e => setConfirm({ member: m, role: e.target.value as Role, remove: false })}>{Object.entries(roleLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button className="danger-outline" disabled={busy} onClick={() => setConfirm({ member: m, role: m.role, remove: true })} aria-label={`${m.name} entfernen`}>Entfernen</button></div>}</div>)}
 {confirm && <div className="team-confirm" role="group" aria-label="Teamänderung bestätigen"><p>{confirm.remove ? `${confirm.member.name} verliert den Zugang zu diesem Arbeitsbereich. Bestehende Protokolle bleiben erhalten.` : `Rolle von ${confirm.member.name} auf „${roleLabels[confirm.role]}“ ändern?`}</p><div className="team-actions"><button className="secondary" disabled={busy} onClick={() => setConfirm(null)}>Abbrechen</button><button className="primary" disabled={busy} onClick={() => run(() => changeMember(data, confirm.member, confirm.role, confirm.remove, cloud))}>Änderung bestätigen</button></div></div>}
 </section>
 {admin && <section className="panel"><h2>Teammitglied einladen</h2><p className="muted">Der Link gilt sieben Tage und kann nur mit der bestätigten E-Mail-Adresse angenommen werden.</p><form onSubmit={invite}><fieldset className="inspection-fields" disabled={busy}><div className="form-grid"><label>Name<input name="name" required maxLength={120} /></label><label>E-Mail<input name="email" type="email" required /></label><label className="span-2">Rolle<select name="role" defaultValue="driver">{Object.entries(roleLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><button className="primary mt" disabled={busy}>Einladungslink erstellen</button></fieldset></form>
 {link && <div className="invite-link"><label>Einladungslink<input readOnly value={link} onFocus={e => e.target.select()} /></label><button className="secondary" onClick={async () => { try { await navigator.clipboard.writeText(link); setCopied(true); } catch { setError('Link bitte aus dem Feld kopieren.'); } }}>{copied ? 'Kopiert' : 'Link kopieren'}</button><p className="muted small">{cloud ? 'Teile diesen Link mit der eingeladenen Person. Es wurde keine Einladungs-E-Mail versendet.' : 'Demo-Link: Die Annahme ist erst mit Cloud-Anbindung möglich.'}</p></div>}
 <h2 className="mt">Offene Einladungen</h2>{pending.map(i => <div className="team-member" key={i.id}><div><strong>{i.name}</strong><p className="muted small">{i.email} · {roleLabels[i.role]}</p><p className="muted small">Gültig bis {new Date(i.expires_at).toLocaleDateString('de-DE')}</p></div><button className="danger-outline" disabled={busy} onClick={() => { setLink(''); void run(() => revokeInvitation(data, i.id, cloud)); }}>Einladung widerrufen</button></div>)}{!pending.length && <p className="muted">Keine offenen Einladungen.</p>}</section>}
 <section className="panel"><h2>Rollen und Berechtigungen</h2><dl><dt>Administrator</dt><dd>Teamverwaltung und Disposition</dd><dt>Disposition</dt><dd>Fahrzeuge, Fahrer, Aufträge und Protokolle</dd><dt>Fahrer</dt><dd>Protokolle eigener zugewiesener Aufträge</dd><dt>Lesend</dt><dd>Listen, Historie und Protokolle ansehen</dd></dl><p className="muted small">Mindestens ein Administrator bleibt erhalten. Fahrer mit offenen Aufträgen müssen zuerst neu zugewiesen werden.</p></section></div>;
}
