'use client';
/* eslint-disable @next/next/no-img-element -- private, short-lived URLs must not enter the image optimizer cache */
import { useCallback, useEffect, useRef, useState } from 'react';
import { Data, Vehicle, VehicleAsset, VehicleKey } from '@/lib/domain';
import { assetUrl, changeKey, keyActionLabels, keyStateLabels, removeAsset, uploadAsset, validateAsset } from '@/lib/vehicle-records';
export interface QueuedAsset {file:File;kind:VehicleAsset['kind']}
interface UploadItem extends QueuedAsset {id:string;progress:number;status:'pending'|'uploading'|'done'|'error';error:string}
function AssetCard({asset,cloud,manage,onRemove}:{asset:VehicleAsset;cloud:boolean;manage:boolean;onRemove:()=>void}) {
 const [url,setUrl]=useState(''),[error,setError]=useState('');
 async function open(download=false){try{const link=await assetUrl(asset,cloud);if(download){const a=document.createElement('a');a.href=link;a.download=asset.name;a.target='_blank';a.rel='noopener';a.click();}else setUrl(link);setError('');}catch(e){setError(e instanceof Error?e.message:'Datei konnte nicht geladen werden.');}}
 return <article className="asset-card"><strong>{asset.name}</strong><span className="muted small">{asset.kind==='photo'?'Fahrzeugfoto':asset.kind==='registration'?'Fahrzeugschein':'Dokument'} · {(asset.size/1024/1024).toFixed(1)} MB</span><div className="record-actions"><button className="text-button" onClick={()=>void open()}>Vorschau</button><button className="text-button" onClick={()=>void open(true)}>Download</button>{manage&&<button className="text-button" onClick={onRemove}>Entfernen</button>}</div>{url&&(asset.mime==='application/pdf'?<iframe title={asset.name} src={url}/>:<img src={url} alt={asset.name} onError={()=>{setUrl('');setError('Vorschau abgelaufen. Bitte erneut öffnen.');}}/>)}{error&&<p role="alert">{error}</p>}</article>;
}
export function VehicleRecord({data,vehicle,cloud,manage,initialFiles=[],onChange,onQueueConsumed}:{data:Data;vehicle:Vehicle;cloud:boolean;manage:boolean;initialFiles?:QueuedAsset[];onChange:(data:Data)=>void;onQueueConsumed:()=>void}) {
 const [uploads,setUploads]=useState<UploadItem[]>([]);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[remove,setRemove]=useState<VehicleAsset|null>(null),[editing,setEditing]=useState<VehicleKey|null>(null);
 const processedFiles=useRef<QueuedAsset[]|null>(null),latest=useRef(data);
 useEffect(()=>{latest.current=data;},[data]);
 const keys=(data.keys??[]).filter(k=>k.vehicle_id===vehicle.id),holder=data.holders?.find(h=>h.vehicle_id===vehicle.id);
 const runUploads=useCallback(async(items:UploadItem[])=>{setBusy(true);setError('');let current=latest.current;for(const item of items.filter(i=>i.status!=='done')){
  const patch=(values:Partial<UploadItem>)=>setUploads(old=>old.map(i=>i.id===item.id?{...i,...values}:i));patch({status:'uploading',error:'',progress:0});
  try{current=await uploadAsset(current,vehicle,item.file,item.kind,cloud,progress=>patch({progress}));onChange(current);patch({status:'done',progress:100});}catch(e){patch({status:'error',error:e instanceof Error?e.message:'Upload fehlgeschlagen.'});}
 }setBusy(false);},[vehicle,cloud,onChange]);
 useEffect(()=>{if(initialFiles.length&&processedFiles.current!==initialFiles){processedFiles.current=initialFiles;const items:UploadItem[]=initialFiles.map(item=>({...item,id:crypto.randomUUID(),progress:0,status:'pending',error:''}));void Promise.resolve().then(()=>{setUploads(old=>[...old,...items]);onQueueConsumed();return runUploads(items);});}},[initialFiles,runUploads,onQueueConsumed]);
 function queue(files:FileList|null,kind:VehicleAsset['kind']){try{const values=Array.from(files??[]);values.forEach(file=>validateAsset(file,kind));setUploads(old=>[...old,...values.map(file=>({id:crypto.randomUUID(),file,kind,progress:0,status:'pending' as const,error:''}))]);setError('');}catch(e){setError(e instanceof Error?e.message:'Ungültige Datei.');}}
 async function keyAction(action:string,key:VehicleKey|null,values:Record<string,string>={}){setBusy(true);setError('');try{onChange(await changeKey(latest.current,vehicle,key?.id??crypto.randomUUID(),action,values,cloud));setEditing(null);}catch(e){setError(e instanceof Error?e.message:'Schlüsselvorgang fehlgeschlagen.');}finally{setBusy(false);}}
 function saveKey(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);void keyAction(editing?'edit':'create',editing,{label:String(f.get('label')),identifier:String(f.get('identifier')),location:String(f.get('key_location'))});if(!editing)event.currentTarget.reset();}
 return <div className="vehicle-record"><section className="panel"><h2>Fahrzeugakte</h2><dl className="record-summary"><div><dt>Baujahr</dt><dd>{vehicle.build_year??'Nicht erfasst'}</dd></div><div><dt>Erstzulassung</dt><dd>{vehicle.first_registration??'Nicht erfasst'}</dd></div></dl>{holder&&<div className="holder-details"><h3>Fahrzeughalter</h3><strong>{holder.name||'Nicht erfasst'}</strong><p className="preserve-lines">{holder.address}</p><p>{holder.contact}</p></div>}{error&&<p className="alert" role="alert">{error}</p>}</section>
 <section className="panel"><h2>Fotos und Dokumente</h2>{manage&&<fieldset disabled={busy} className="record-fields"><label>Fahrzeugfotos<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>{queue(e.target.files,'photo');e.target.value='';}}/></label><label>Fahrzeugschein<input type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>{queue(e.target.files,'registration');e.target.value='';}}/></label><label>Weitere Dokumente<input type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>{queue(e.target.files,'document');e.target.value='';}}/></label><p className="muted small">Maximal 10 MB je Datei. Dokumente sehen nur Disposition und aktuell zugeteilte Fahrer.</p></fieldset>}
 {uploads.map(item=><div className="upload-item" key={item.id}><strong>{item.file.name}</strong><progress max="100" value={item.progress}/><span role="status">{item.status==='done'?'Gespeichert':item.status==='uploading'?`${item.progress} % · Wird hochgeladen`:item.status==='error'?item.error:'Bereit zum Hochladen'}</span>{item.status==='error'&&<button disabled={busy} className="secondary" onClick={()=>void runUploads([item])}>Erneut versuchen</button>}{item.status==='pending'&&<button disabled={busy} className="text-button" onClick={()=>setUploads(old=>old.filter(i=>i.id!==item.id))}>Auswahl entfernen</button>}</div>)}{uploads.some(i=>i.status==='pending')&&<button disabled={busy} className="primary mt" onClick={()=>void runUploads(uploads.filter(i=>i.status==='pending'))}>Ausgewählte Dateien hochladen</button>}
 <div className="asset-grid">{(data.assets??[]).filter(a=>a.vehicle_id===vehicle.id).map(a=><AssetCard key={a.id} asset={a} cloud={cloud} manage={manage} onRemove={()=>setRemove(a)}/>)}</div>{!(data.assets??[]).some(a=>a.vehicle_id===vehicle.id)&&<p className="muted">Keine zugänglichen Anhänge vorhanden.</p>}
 {remove&&<div className="remove-confirm" role="alert"><p>„{remove.name}“ aus der Fahrzeugakte entfernen?</p><button disabled={busy} className="danger" onClick={async()=>{setBusy(true);try{onChange(await removeAsset(latest.current,remove,cloud));setRemove(null);}catch(e){setError(e instanceof Error?e.message:'Entfernen fehlgeschlagen.');}finally{setBusy(false);}}}>Datei entfernen</button><button className="secondary" onClick={()=>setRemove(null)}>Behalten</button></div>}</section>
 <section className="panel"><h2>Schlüssel</h2><p className="muted">{vehicle.keys_recorded?`${keys.filter(k=>k.state!=='retired').length} erfasst · ${keys.filter(k=>k.state==='available').length} vorhanden · ${keys.filter(k=>k.state==='issued').length} ausgegeben · ${keys.filter(k=>k.state==='lost').length} verloren`:'Schlüsselbestand nicht erfasst'}</p>
 {manage&&<fieldset disabled={busy}><form className="key-form" onSubmit={saveKey} key={editing?.id??'new'}><h3>{editing?'Schlüssel bearbeiten':'Schlüssel hinzufügen'}</h3><label>Bezeichnung<input name="label" required maxLength={120} defaultValue={editing?.label} placeholder="z. B. Hauptschlüssel"/></label><label>Kennung (optional)<input name="identifier" maxLength={120} defaultValue={editing?.identifier}/></label><label>Aufbewahrungsort<input name="key_location" maxLength={240} defaultValue={editing?.location} placeholder="z. B. Schlüsselschrank A"/></label><button className="secondary">{editing?'Schlüssel speichern':'Schlüssel hinzufügen'}</button>{editing&&<button type="button" className="text-button" onClick={()=>setEditing(null)}>Abbrechen</button>}</form>{!vehicle.keys_recorded&&!keys.length&&<button className="text-button mt" onClick={()=>void keyAction('record_empty',null)}>Bestätigen: keine Schlüssel vorhanden</button>}</fieldset>}
 {keys.map(k=><article className="key-card" key={k.id}><strong>{k.label}</strong><p>{k.identifier} · {keyStateLabels[k.state]}</p><p className="muted">{k.location||'Aufbewahrungsort nicht erfasst'}{k.custodian?' · '+k.custodian:''}</p>{manage&&<><button disabled={busy} className="text-button" onClick={()=>setEditing(k)}>Bearbeiten</button>{k.state!=='retired'&&<form className="key-movement" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void keyAction(String(f.get('action')),k,{person:String(f.get('person')),location:String(f.get('location'))});}}><label>Person<input name="person" required maxLength={120} placeholder="Name der Person"/></label><label>Neuer Aufbewahrungsort<input name="location" maxLength={240} defaultValue={k.location}/></label><label>Vorgang<select name="action">{k.state==='available'&&<option value="issue">Ausgeben</option>}{['issued','lost'].includes(k.state)&&<option value="return">Zurücknehmen</option>}{k.state!=='lost'&&<option value="lost">Verlust dokumentieren</option>}<option value="retire">Ausmustern</option></select></label><button disabled={busy} className="secondary">Vorgang speichern</button></form>}</>}</article>)}
 <h3 className="mt">Schlüsselhistorie</h3>{(data.key_movements??[]).filter(m=>m.vehicle_id===vehicle.id).sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(m=><p className="key-history" key={m.id}>{keyActionLabels[m.action]??m.action} · {m.key_label??'Schlüssel'} · {m.person} · {m.location}<span className="muted small">{new Date(m.created_at).toLocaleString('de-DE')} · dokumentiert von {m.actor_name}</span></p>)}</section></div>;
}
