'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import {CarFront} from 'lucide-react';
import {Data,Vehicle} from '@/lib/domain';
import {coverImage,setCover,vehicleImages,VehicleImage} from '@/lib/vehicle-images';
import {supabase} from '@/lib/supabase';
type PhotoProps={image?:VehicleImage;org:string;cloud:boolean;large?:boolean};
export function VehiclePhoto(props:PhotoProps){return <VehiclePhotoContent key={[props.image?.id,props.image?.path,props.org,props.cloud,props.large].join('|')} {...props}/>;}
function VehiclePhotoContent({image,org,cloud,large=false}:{image?:VehicleImage;org:string;cloud:boolean;large?:boolean}){const [url,setUrl]=useState(''),[failed,setFailed]=useState(false),ref=useRef<HTMLDivElement>(null);const path=image?.path,bucket=image?.bucket,source=image?.url;useEffect(()=>{let live=true,objectUrl='';if(!path&&!source)return;const observer=new IntersectionObserver(entries=>{if(!entries.some(e=>e.isIntersecting))return;observer.disconnect();if(!cloud){setUrl(source??'');return;}void(async()=>{const session=(await supabase!.auth.getSession()).data.session;const r=await fetch('/api/vehicle-image',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session?.access_token},body:JSON.stringify({organization_id:org,bucket,path,large})});if(!r.ok)throw Error('image');objectUrl=URL.createObjectURL(await r.blob());if(live)setUrl(objectUrl);else URL.revokeObjectURL(objectUrl);})().catch(()=>{if(live)setFailed(true);});},{rootMargin:'150px'});observer.observe(ref.current!);return()=>{live=false;observer.disconnect();if(objectUrl)URL.revokeObjectURL(objectUrl);};},[path,bucket,source,org,cloud,large]);return <div ref={ref} className={large?'vehicle-photo large':'vehicle-photo'}>{url?<Image src={url} alt={image?.label??'Fahrzeugfoto'} width={large?1280:320} height={large?960:240} unoptimized/>:<span><CarFront size={large?42:22}/>{large&&<small>{failed?'Bild derzeit nicht verfügbar':'Fahrzeugbild'}</small>}</span>}</div>;}
export function VehicleGallery({data,vehicle:v,cloud,manage,onChange}:{data:Data;vehicle:Vehicle;cloud:boolean;manage:boolean;onChange:(next:Data)=>void}){const images=vehicleImages(data,v),cover=coverImage(data,v),[selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const current=images.find(i=>i.id===selected)??cover;async function choose(image:VehicleImage|null){setBusy(true);setError('');try{onChange(await setCover(data,v,image,cloud));}catch(e){setError(e instanceof Error?e.message:'Änderung fehlgeschlagen.');}finally{setBusy(false);}}return <section className="panel vehicle-gallery"><div className="section-heading"><h2>Fahrzeugbilder</h2>{manage&&v.cover_id&&<button className="text-button" disabled={busy} onClick={()=>choose(null)}>Automatisches Titelbild</button>}</div>{error&&<p className="alert">{error}</p>}<VehiclePhoto image={current} org={data.organization.id} cloud={cloud} large/>{current&&<div className="gallery-caption"><p>{current.label} · {new Date(current.created_at).toLocaleString('de-DE')}</p>{manage&&<button className="secondary" disabled={busy||current.id===v.cover_id} onClick={()=>choose(current)}>Als Titelbild verwenden</button>}</div>}<div className="vehicle-gallery-grid">{images.map(image=><button key={image.id} className={current?.id===image.id?'selected':''} onClick={()=>setSelected(image.id)}><VehiclePhoto image={image} org={data.organization.id} cloud={cloud}/><span>{image.label}</span><small>{new Date(image.created_at).toLocaleDateString('de-DE')}</small></button>)}</div>{!images.length&&<p className="muted">Fahrzeugfotos und Bilder abgeschlossener Protokolle erscheinen hier.</p>}</section>;}
